(feat) Add print receipt button
palladiumkenya/kenyaemr-esm-3.x pull request #109
Opened 2023-12-17 20:38 UTC by CynthiaKamau

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Add printable receipt component

## Screenshots
- https://www.loom.com/share/361f15d43d8a41e486d406abdd882fdc?sid=0a5576c7-fca8-452d-abc8-4a4754bbfd38

*None.*

## Related Issue

*None.*

## Other

*None.*

2023-12-18 06:24 UTC, donaldkibet requested changes
Thanks @CynthiaKamau LGTM just once suggestion, please also include unit test for the functionality added. Thanks!

2023-12-18 06:24 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/printable-invoice/print-receipt.component.tsx
> +      </ConfigurableLink>{' '}
I think this isn't right we should just have the function to navigate to print same as done to print invoice that is using `onClick` handle of the button. We should also only print receipt for fully paid or partially paid invoices.

```ts
     <Button
      kind="secondary"
      className={styles.button}
      onClick={() => navigate({ to: `\${openmrsBase}/ws/rest/v1/cashier/receipt?billId=${billId}` })}
      size="md"
      renderIcon={(props) => <Printer size={24} {...props} />}>
      {t('printReceipt', 'Print receipt')}
    </Button>
```

2023-12-18 12:03 UTC, CynthiaKamau commented on packages/esm-billing-app/src/invoice/printable-invoice/print-receipt.component.tsx
> +      </ConfigurableLink>{' '}
The endpoint renders a file, basically the receipt is generated from the backend, but let me explore ways to preview it before its dowloaded

2023-12-20 08:32 UTC, donaldkibet approved these changes

2023-12-20 08:32 UTC, merged