Enhanced adherence in clinical view
palladiumkenya/kenyaemr-esm-3.x pull request #111
Opened 2023-12-19 09:57 UTC by gabriel090

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

![adherence](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8075969/47dcd553-4738-4ac6-a5e7-870b1536e5b7)

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2023-12-22 06:22 UTC, makombe commented
@gabriel090  Please resolve the conflicts. Thanks

2023-12-22 06:27 UTC, donaldkibet requested changes
Thanks @gabriel090 Great work 🚀 let some suggestions.

2023-12-22 06:27 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
> +  title: 'Adherence',
We should have this rename to `enhanced adherence` for UI naming

2023-12-22 06:27 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/enhanced-adherence/adherence-table.component.tsx
> +                            // onClick={}
```suggestion

```

2023-12-22 06:27 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/enhanced-adherence/adherence-table.component.tsx
> +                if (!uniqueDates.has(o?.obsDatetime) && o?.concept?.uuid === '1639AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA') {
should avoid hard coding concepts like this in code

2023-12-22 06:27 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/enhanced-adherence/enhanced-adherence.components.tsx
> +  const headerTitle = t('enhancedadherence', 'Advanced Enhanced Adherence');
```suggestion
  const headerTitle = t('enhancedadherence', 'Enhanced Adherence');
```
to have consistency same as☝🏽

2023-12-22 07:34 UTC, ojwanganto commented
@gabriel090 I think we may need to add more columns to the table provided. Do we capture adherence score anywhere? or anything like final outcome? Kindly work with BA

2024-07-11 08:24 UTC, donaldkibet commented
@Gabriel090, I am closing this PR for now as it has been inactive for some time. I believe it would be beneficial to start afresh on the implementation of this feature.

Thank you for your understanding.

2024-07-11 08:24 UTC, closed without merging