Develop Family History Clinical View
palladiumkenya/kenyaemr-esm-3.x pull request #125
Opened 2024-01-04 18:45 UTC by gabriel090

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Create a comprehensive Family History Clinical View within openmrs 3.x to facilitate a quick understanding of a patient's familial health background. The view should include Family Member Details:

    Display relation/relative; 

1. Names, 

2. Ages,

 3. Chronic conditions/ Hereditary  

4. alive status, and cause of death (if applicable).

    Include a Family Tree Diagram for a visual representation of family structure and relationships

    Allow addition of relation for update of their history depending on the case

#
![family-history-clinc-view](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8075969/78b0076a-f6af-4631-9d54-db9f22f4b02d)
# Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-01-04 19:47 UTC, ojwanganto requested changes
I am still not clear on whether this component should be named family history or just relationships. The BA team can help guide us

2024-01-04 19:47 UTC, ojwanganto commented on packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
> +  title: 'Family History Dashboard',
There was a suggestion that we drop Dashboard from the name. Just call it family history

2024-01-04 19:47 UTC, ojwanganto commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +const CHRRONIC_CONCEPT_UUID = '1284AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
I noted a pattern to have such defined in a constants file and reference them in the component. That way we'll just worry about a single place to maintain in case of any changes. @donaldkibet can add. I may be off :)

2024-01-19 09:40 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/types/index.ts
> +}
This concept map ought to exist in the config schema file (and not as an enum).

2024-01-19 09:41 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +      key: 'chronicleDisease',
Key should be `chronicDisease`

2024-01-19 09:43 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/hooks/useFamilyHistory.ts
> +    isValidatingRelationShips: isValidating,
Nit: `relationship` instead of `relationShip`

2024-01-19 09:44 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +        //  causeOfDeath: <PatientChronicDiseases patientUuid={patientUuid} conceptUuid={FamilyHistoryConcepts.cause_of_death} />,
Looks like this can be removed

2024-01-19 09:45 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +    return <EmptyState headerTitle={headerTitle} displayText={headerTitle} />;
```suggestion
    return <EmptyState headerTitle={headerTitle} displayText="family history data" />;
```

which gives you:

![CleanShot 2024-01-19 at 12  45 32@2x](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8509731/5b5062f7-7619-4440-bb74-d4ef464838a3)

2024-01-19 09:48 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
>  };
Not related to you work, but it'd be cool to rename this navGroup to `Clinical views` instead of `Clinical view` https://github.com/palladiumkenya/kenyaemr-esm-3.x/blob/08a242f2f6eb9672eb882bee7535a887d822d7e8/packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx#L2

2024-01-19 09:51 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +              headers={headers}
```suggestion
            <DataTable
              useZebraStyles
              rows={tableRows ?? []}
              headers={headers}
```

2024-01-19 09:52 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +              headers={headers}
So we can leverage `useZebraStyles` table striping.

2024-01-22 22:09 UTC, denniskigen commented on packages/esm-patient-clinical-view-app/src/family-history/family-history.component.tsx
> +const CHRRONIC_CONCEPT_UUID = '1284AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
It's preferable to move this over to the config schema.

2024-01-23 03:29 UTC, ojwanganto commented
@denniskigen thanks so much for this. I have just noted that the original code pulled chronic illnesses from obs. I would wish we moved this to pull from conditions resource instead. That is future-proof. What do you think?

2024-01-23 05:55 UTC, donaldkibet approved these changes
LGTM Thanks @gabriel090 & @denniskigen 🚀  merging this in. Will address follow up issues

2024-01-23 08:32 UTC, denniskigen commented
@ojwanganto, yeah, it looks a lot more preferable to me to get that data from the conditions resource as well.

2024-01-23 09:57 UTC, merged