(feat) Update billing to new workflow on check
palladiumkenya/kenyaemr-esm-3.x pull request #171
Opened 2024-02-20 00:36 UTC by donaldkibet

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

This PR updates the billing workflow by having two categories. 
Exempted and non-exempted patient

## Screenshots
![Peek 2024-02-20 03-29](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/68b9af61-e666-4df0-b400-bbbcb748cccf)

## Related Issue

*None.*

## Other

*None.*

2024-02-21 07:00 UTC, ojwanganto requested changes
@donaldkibet please check if my comments hold water. Thanks

2024-02-21 08:51 UTC, jecihjoy commented on packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
> +                  items={[{ uuid: '162277AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', display: 'In Prision' }]}
@ojwanganto the plan here was to change from using concepts to just free text but managed using a drop down

2024-02-21 18:33 UTC, ojwanganto commented on packages/esm-billing-app/src/billing-form/visit-attributes/visit-attributes-form.component.tsx
> +                  items={[{ uuid: '162277AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', display: 'In Prision' }]}
ok

2024-02-21 20:57 UTC, ojwanganto commented
Are we good to go with this one? @donaldkibet @makombe @jecihjoy

2024-02-22 13:17 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-waiver/utils.ts
> +    instanceType: paymentModes?.find((mode) => mode.name.toLowerCase().includes('waiver'))?.uuid,
Attempt to remove hard coding waiver. The waiver payment name needs to be named appropriately from the backend

2024-02-22 13:51 UTC, ojwanganto commented
Thank you. I think we can go ahead and merge this in.

2024-02-22 13:54 UTC, ojwanganto commented on packages/esm-billing-app/src/billable-services/bill-waiver/utils.ts
> +    instanceType: paymentModes?.find((mode) => mode.name.toLowerCase().includes('waiver'))?.uuid,
This should work. The backend module should ensure this is not changed. We are good with this

2024-02-22 13:56 UTC, jecihjoy approved these changes

2024-02-22 13:56 UTC, merged