Create search function instead of the dropdown function in billable s…
palladiumkenya/kenyaemr-esm-3.x pull request #176
Opened 2024-03-05 21:44 UTC by gabriel090

Create a Search function instead of the dropdown function in billable services in the check-in Form

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).
Create a Search function instead of the dropdown function in billable services in the check -in Form

## Summary

## Screenshots
Image Before when it was using a dropdown function
![search_before](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8075969/8366d118-7445-41db-96b1-8d099ec501e9)

image when the search function was implemented
![search_after](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/8075969/568fe171-a842-488a-9499-228a032a3d43)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-03-05 21:46 UTC, ojwanganto commented
This is nice, thanks. I will let others review it.

2024-03-06 08:28 UTC, donaldkibet requested changes

2024-03-06 08:28 UTC, donaldkibet commented on packages/esm-billing-app/src/billing-form/billing-checkin-form.component.tsx
>            </Layer>
Thanks @gabriel090, I think the best approach is to extract this functionality to a component. 
e.g 
```tsx 
<BilliableServices onBillItemSelected={handleSelectedBillItem}/>
```

In this component, have the logic to search and select the billiable item

2024-03-08 04:38 UTC, donaldkibet approved these changes

2024-03-08 04:39 UTC, merged