Feat/mpesa integration
palladiumkenya/kenyaemr-esm-3.x pull request #207
Opened 2024-04-22 03:28 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- added the validation to initiate modal and default value as the pending bill tables cashier to edit if the client has less on the mpesa account on the amount text field
- added  generation of tokens functionality for authenticating Daraja API calls
- added function formats a phone number to startwith the country code 254
-  added validation and initialization of stk push to client phone

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-04-22 05:11 UTC, donaldkibet requested changes
Thanks @its-kios09, Left some suggestions. Also include a short video of the changes you have made

2024-04-22 05:11 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment.resource.ts
> +    const consumer_secret = 'C82O7IoDR8onqibYGRQpV2xIaGRWY7Ozr7NbnOAbTuj8SCaJGMbTNhh0qBrBQ1VO';
Derive these values from the env file.

2024-04-22 05:11 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment.resource.ts
> +    const response = await openmrsFetch(authorization_url, { method: 'GET', headers });
Not sure where `openmrsFetch` would here because it appends the server url and openmrs authentication headers.

2024-04-22 05:11 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment.resource.ts
> +    console.log('[itskios-09]: Generated Access Token from initiateStkPush:', access_token);
We need this removed

2024-04-22 05:11 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/utils.ts
> +  var _phone = '';
using var for variable declaration isn't recommended. use either let or const

2024-04-26 00:54 UTC, its-kios09 commented
@donaldkibet okay, lemme work on it

2024-04-26 00:54 UTC, closed without merging