Process stk push payment transaction
palladiumkenya/kenyaemr-esm-3.x pull request #211
Opened 2024-05-13 16:28 UTC by jecihjoy

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
[Screencast from 13-05-2024 07:23:57 ALASIRI.webm](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/18227275/4ff40bea-85d3-42de-91c7-3a27d0a34bcc)

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-05-14 07:46 UTC, ojwanganto commented
Thanks, @jecihjoy. I will ask @donaldkibet and @makombe to provide their reviews.

2024-05-15 12:17 UTC, donaldkibet requested changes
Thanks @jecihjoy, left some suggestions and improvement. Given the critical part this functions plays in the EMR it would be great to have some Unit test at the minimum on these feature. Thanks!

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
> +      callBackUrl: 'https://9cf8-196-106-176-56.ngrok-free.app/api/confirmation-url',
We should either make this callback url a config or global property to ensure this feature is always working

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
> +                    placeholder={t('phoneNumber', 'Phone Number')}
We need to validate this phone number e.g I can enter a phone in these two scenarios
1. `0720XXXXXX`
2. `254700XXXXXX`

Of the two its good to be explicit about which one we are going to use.

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
> +            <Button type="submit" className={styles.button} onClick={handleSubmit(onSubmit)}>
using the form submission to handle initiating the payment isn't the best case. We also need to disable the button to prevent users from initiating multiple request. At the moment there is no communication of whether the request is being processed.

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment-transaction/show-payment-transaction.component.tsx
> +const ShowPaymentTransaction: React.FC<ShowPaymentTransactionProps> = ({ closeModal, statement }) => {
I don't think we need this component, We can leverage the `toast` provided by OpenMRS esm core to show that the payment is successful. e.g

```tsx
showToast(
{
  title: t('paymentStatusTitle','Payment status'),
  subTitle: statement,
  kind: 'success'
}
)
```

This is just an example

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment-transaction/show-payment-transaction.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
We should not be using import, use carbon styles
```suggestion
```

2024-05-15 12:17 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/payment.resource.ts
> +  const { data, isLoading, error, mutate } = useSWR<{ data: { results: Array<any> } }>(url, openmrsFetch, swrOption);
Please provide proper types for the results, this make maintaining the code easy to understand

2024-05-15 12:25 UTC, donaldkibet commented
@jecihjoy, could you please ensure that your PR includes a clear and descriptive title along with a proper summary of the changes, following our community guidelines? This will make it easier to maintain the project in the future. Thank you!
[contribution guide for OpenMRS 3.x](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines)

2024-07-04 10:51 UTC, donaldkibet commented
This is stale, closing this

2024-07-04 10:51 UTC, closed without merging