Enhancement on the LIPANA MPESA STK push - Error Handling
palladiumkenya/kenyaemr-esm-3.x pull request #227
Opened 2024-06-10 22:40 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- (feat) added error handling by add inline notification 

## Screenshots
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/67967749/14209079-456e-4a44-adb4-253a903c46e9

*None.*

## Related Issue

*None.*

## Other
- To run the LIPA NA MPESA you need credentials from daraja API which included the following
**consumer_Key
consumer_Sercet
Passkey
Authorization_URL
Initiate_URL**

- To run it on local instance 
`google-chrome --user-data-dir=/tmp --disable-web-security
`

2024-06-11 05:52 UTC, makombe commented
Thanks @its-kios09. Something that has just come to mind can we ensure that `Initiate payment` is only shown where payment method is MPESA. This can happen in a follow up PR not necessary on this. Thanks

2024-06-11 10:45 UTC, ojwanganto commented
Thanks, @its-kios09. Should we rename the "Initiate payment" button to read something processing payment?

2024-06-11 11:00 UTC, its-kios09 commented
@makombe @ojwanganto  I was thinking the payment method is we use it for reconciliation of payments due to the ref number textfield or what do you think?
On the renaming, maybe we should look for a simple name

2024-06-11 16:14 UTC, ojwanganto commented
You are right, @its-kios09.

2024-06-11 18:12 UTC, its-kios09 commented
Let me work on the suggestion

2024-06-11 21:16 UTC, ojwanganto commented
@its-kios09 you should not close the PR. I believe you can still just update the PR with additional changes.

2024-06-12 11:38 UTC, ojwanganto commented on packages/esm-billing-app/src/m-pesa/mpesa-resource.tsx
> +export const usePaymentModes = () => {
Should this file be named something else other than mpesa? I can see it has other payment modes other than mpesa.

2024-06-12 12:33 UTC, ojwanganto commented on packages/esm-billing-app/src/invoice/invoice.component.tsx
> +import MakeClaims from '../claims/make-claims.component';
Has this been used in here?

2024-06-12 13:27 UTC, its-kios09 commented on packages/esm-billing-app/src/invoice/invoice.component.tsx
> +import MakeClaims from '../claims/make-claims.component';
Nop, I Have decided to combine mpesa integration and claims functionality on the same branch as Donald suggestion

2024-06-13 04:25 UTC, ojwanganto commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-header/claims-header.component.tsx
> +  console.log('billUuid', bill);
you will not need these

2024-06-13 04:25 UTC, ojwanganto commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-dashboard.component.tsx
> +          description="Loading patient header..."
Should we translate this?

2024-06-13 04:26 UTC, ojwanganto commented on packages/esm-billing-app/src/invoice/invoice.component.tsx
> +import MakeClaims from '../claims/make-claims.component';
OK

2024-06-13 04:27 UTC, ojwanganto commented on packages/esm-billing-app/translations/en.json
> +  "Error": "",
What does this do?

2024-06-13 06:38 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-header/claims-header.component.tsx
> +  console.log('billUuid', bill);
I have remove them on my next commit

2024-06-13 06:39 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-dashboard.component.tsx
> +          description="Loading patient header..."
I will be handling translation today

2024-06-13 06:39 UTC, its-kios09 commented on packages/esm-billing-app/translations/en.json
> +  "Error": "",
Let me look at it

2024-06-13 19:25 UTC, donaldkibet requested changes

2024-06-13 19:25 UTC, donaldkibet commented on package.json
> +    "@openmrs/esm-framework": "^5.6.1-pre.1895",
```suggestion
    "@openmrs/esm-framework": "next",
```
we only need to update the `yarn.lock` file for such updates

2024-06-13 19:25 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-dashboard.component.tsx
> +    </>
```suggestion    
      <ClaimsHeader patient={patient} bill={bill} />    
```

2024-06-13 19:25 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/claims-wrap/claims-main-component.tsx
> +const ClaimMainComponent: React.FC<ClaimsMainHeaderProps> = ({ bill }) => {
```suggestion
const ClaimMainComponent: React.FC<ClaimsMainProps> = ({ bill }) => {
```

2024-06-13 23:33 UTC, its-kios09 commented on package.json
> +    "@openmrs/esm-framework": "^5.6.1-pre.1895",
I have issue with navigate i decided to use` yarn up openmrs @openmrs/esm-framework` and it worked

2024-06-13 23:34 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/claims-dashboard/claims-dashboard.component.tsx
> +    </>
sorted

2024-06-13 23:34 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/claims-wrap/claims-main-component.tsx
> +const ClaimMainComponent: React.FC<ClaimsMainHeaderProps> = ({ bill }) => {
sorted

2024-06-20 06:36 UTC, donaldkibet approved these changes

2024-06-20 08:47 UTC, donaldkibet commented
Thanks @its-kios09, merging this in

2024-06-20 08:47 UTC, merged