Feature stk push
palladiumkenya/kenyaemr-esm-3.x pull request #241
Opened 2024-06-24 10:59 UTC by amosmachora

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
I have integrated the code with the existing payments aggregator see [here](https://github.com/palladiumkenya/payments-aggregator).  I have also created a polling mechanism to get the state of the current request and update the UI appropriately.

## Screenshots

https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/81857018/58f283b5-6418-45f3-8104-e7be9ae37a3f

## Related Issue

*None.*

## Other
Well since we are using the daraja sandbox api , as i explained during the meeting we cannot guarantee that safaricom will hit your callback url and unfortunately that`s what I use to update the request status. This issue is not there in production daraja API though. So advice accordingly. If i should pause that functionality until prod well and good, but for me leaving it there since it will work on prod seems the most appropriate approach.

2024-06-24 14:05 UTC, donaldkibet requested changes
Thanks @amosmachora, Just a few suggestions.

2024-06-24 14:05 UTC, donaldkibet commented on packages/esm-billing-app/src/helpers/functions.ts
> +export const getErrorMessage = (err: any) => {
It would be good to have the type for the error message

2024-06-24 14:05 UTC, donaldkibet commented on packages/esm-billing-app/src/helpers/functions.ts
> +  return 'an unknown error occurred';
Is it possible to have translation for this

```suggestion
  return t('unKnownErrorMsg','An unknown error occurred')
```
```suggestion
  return 'an unknown error occurred';
```

2024-06-24 14:05 UTC, donaldkibet commented on packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
> +  }, [requestData.requestId, requestData.requestStatus]);
Could we extract this logic to a custom hook to keep things on this component simple

2024-06-24 14:05 UTC, donaldkibet commented on packages/esm-billing-app/src/m-pesa/mpesa-resource.tsx
> +// export const MPESA_PAYMENT_API_BASE_URL = 'http://localhost:3000';
```suggestion

```
```suggestion
// export const MPESA_PAYMENT_API_BASE_URL = 'http://localhost:3000';
```

2024-06-24 15:31 UTC, amosmachora commented on packages/esm-billing-app/src/invoice/payments/initiate-payment/initiate-payment.component.tsx
> +  }, [requestData.requestId, requestData.requestStatus]);
On it @donaldkibet .

2024-06-24 15:32 UTC, amosmachora commented on packages/esm-billing-app/src/helpers/functions.ts
> +  return 'an unknown error occurred';
I am still familiarizing yourself with how you guys are doing translations but I assume you guys no better so I`m going to committ this change

2024-06-24 15:34 UTC, amosmachora commented on packages/esm-billing-app/src/helpers/functions.ts
> +export const getErrorMessage = (err: any) => {
Got it. I will use the native ```Error``` type.

2024-06-24 15:49 UTC, ojwanganto commented
Could we also re-label the button once the process is initiated? May be to something like processing request... or something better. Also, we can think of disabling it so that a user doesn't accidentally send multiple requests. 
Are we storing the transaction ID? How is it composed?

2024-06-24 16:29 UTC, amosmachora commented
> Contributor

I will do that. When the initial call to stk push is made we receive a request id which I store in state and then use it to make subsequent requests to thebackend.

2024-06-24 18:48 UTC, ojwanganto commented
Great. Thanks

2024-06-25 08:36 UTC, amosmachora commented
@donaldkibet I have created a custom hook to make the request status. Please check and advice accordingly. Also @ojwanganto should i also save the aggregator URL in environment vars? Or is it fine in this repo.

2024-06-26 13:12 UTC, amosmachora commented
I have added the ability to read the mpesa url from the ```useConfig``` hook.

2024-06-27 09:10 UTC, donaldkibet reviewed
Thanks @amosmachora LGTM

2024-06-27 09:10 UTC, donaldkibet commented on packages/esm-billing-app/src/m-pesa/mpesa-resource.tsx
> +export type RequestStatus = 'INITIATED' | 'COMPLETE' | 'FAILED' | 'NOT-FOUND';
```suggestion
export type RequestStatus = 'INITIATED' | 'COMPLETE' | 'FAILED' | 'NOT-FOUND';
```
Ideally this should be in the types file https://github.com/palladiumkenya/kenyaemr-esm-3.x/blob/main/packages/esm-billing-app/src/types/index.ts

2024-06-27 10:06 UTC, amosmachora commented on packages/esm-billing-app/src/m-pesa/mpesa-resource.tsx
> +export type RequestStatus = 'INITIATED' | 'COMPLETE' | 'FAILED' | 'NOT-FOUND';
On it

2024-06-27 13:24 UTC, donaldkibet approved these changes

2024-06-27 15:53 UTC, donaldkibet commented
@amosmachora am merging this in, we should explore e2e and unit test for the code to prevent regression, since this is an important part of billing

2024-06-27 15:53 UTC, merged