Enhc: filter regimen by age(Adult regimen > age 14 < Child Regimen)
palladiumkenya/kenyaemr-esm-3.x pull request #246
Opened 2024-06-28 08:00 UTC by Justus446

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
**This PR create 2 hooks and enhances the edit regimen functionality :**
1.useCalculateAge:to get the age of a patient(The usePatient hook does not come with age precalculated)
2. useFilteredRegimen: to filter regimens based on age(adult regimens for age > 14, and child regimens for age< or = 14)
3. Drop downs to select regimens for standard-regimen-component and non-standard-regimen-component populated with the relevant regimens based on age

Avoid users selecting child regimens for adults and vice versa by displaying the correct regimen based on age

## Screenshots
![image](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/85983194/a0406ca6-8229-4ad9-8f40-f26942dc7a4f)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-06-28 08:30 UTC, donaldkibet requested changes
Thanks @Justus446 Great enhancement. Left some suggestions. Would also be good if this would be accompanied by Unit test to avoid regression. Thanks!

2024-06-28 08:30 UTC, donaldkibet commented on packages/esm-care-panel-app/src/hooks/useCalculateAge.ts
> +export default useCalculateAge;
we can convert this to a function that calculate age as opposed to using a hook. UseEffect will trigger another re-render.

2024-06-28 08:30 UTC, donaldkibet commented on packages/esm-care-panel-app/src/hooks/useFilteredRegimen.ts
> +}
This should be in the types file

2024-06-28 08:44 UTC, makombe commented on packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
> +  const filteredRegimenByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
```suggestion
  const filteredRegimenLineByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
```

2024-06-28 08:44 UTC, makombe commented on packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
> +            {filteredRegimenByAge.map((line) => (
```suggestion
            {filteredRegimenLineByAge.map((line) => (
```

2024-06-28 08:44 UTC, makombe commented on packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
> +            {filteredRegimenByAge.map((line) => (
```suggestion
            {filteredRegimenLIneByAge.map((line) => (
```

2024-06-28 08:44 UTC, makombe commented on packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
> +  const filteredRegimenByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
```suggestion
  const filteredRegimenLineByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
```

2024-06-28 10:16 UTC, Justus446 commented on packages/esm-care-panel-app/src/hooks/useCalculateAge.ts
> +export default useCalculateAge;
useCalculateAge converted to a hook

2024-06-28 10:17 UTC, Justus446 commented on packages/esm-care-panel-app/src/hooks/useFilteredRegimen.ts
> +}
interfaces moved to types file

2024-06-28 10:17 UTC, Justus446 commented on packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
> +  const filteredRegimenByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
filteredRegimenByAge renamed to filteredRegimenLineByAge

2024-06-28 10:18 UTC, Justus446 commented on packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
> +            {filteredRegimenByAge.map((line) => (
filteredRegimenByAge renamed to filteredRegimenLineByAge

2024-06-28 10:18 UTC, Justus446 commented on packages/esm-care-panel-app/src/regimen-editor/standard-regimen.component.tsx
> +  const filteredRegimenByAge = useFilteredRegimen(matchingCategory?.category, patientAge);
filteredRegimenByAge renamed to filteredRegimenLineByAge

2024-06-28 10:18 UTC, Justus446 commented on packages/esm-care-panel-app/src/regimen-editor/non-standard-regimen.component.tsx
> +            {filteredRegimenByAge.map((line) => (
filteredRegimenByAge renamed to filteredRegimenLineByAge

2024-06-28 11:33 UTC, Justus446 commented
> Thanks @Justus446 Great enhancement. Left some suggestions. Would also be good if this would be accompanied by Unit test to avoid regression. Thanks!

changes made,unit tests coming in another PR

2024-07-01 06:11 UTC, makombe commented
@Justus446  one more thing, after changing the methods to functions, they are no longer hooks and should be removed from the hooks folder into the util file. Thanks

2024-07-03 05:18 UTC, Justus446 commented
> @Justus446 one more thing, after changing the hooks to functions, they are no longer hooks and should be removed from the hooks folder into the `utils.tsx` file. Thanks

Done

2024-07-03 06:18 UTC, makombe approved these changes
LGTM

2024-07-03 06:25 UTC, merged