ADDED TABS TO BILLING AND A SEARCH OPTION FOR ALL PAST PATIENT BILLS
palladiumkenya/kenyaemr-esm-3.x pull request #248
Opened 2024-06-28 11:19 UTC by munania

Uploading BILLING TABS AND SEARCH.mp4…

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-06-28 11:28 UTC, munania commented
Uploading BILLING TABS AND SEARCH.mp4…

2024-06-28 12:07 UTC, donaldkibet requested changes
Thanks @munania, the feature is coming up well. Please provide a screen recording of how the feature is. 🚀

2024-06-28 12:07 UTC, donaldkibet commented on packages/esm-billing-app/src/past-patient-bills/patient-bills-dashboard/patient-bills-dashboard.scss
> +  margin: 2rem 1rem;
```suggestion
  margin: layout.$spacing-03; layout.$spacing-01;
```

2024-06-28 12:07 UTC, donaldkibet commented on packages/esm-billing-app/src/past-patient-bills/filtered-patient-bills.component.tsx
> +    <div style={{ marginTop: '1rem' }}>
```suggestion
    <div className={styles.container}>
```
prefer the styles in css

2024-06-28 12:07 UTC, donaldkibet commented on packages/esm-billing-app/src/past-patient-bills/filtered-patient-bills.component.tsx
> +      <>
use EmptyState component here from either `@openmrs/esm-patient-common-lib` or from `@openmrs/esm-framework` the later is preferred.

2024-06-28 12:07 UTC, donaldkibet commented on packages/esm-billing-app/src/past-patient-bills/filtered-patient-bills.component.tsx
> +  }
Its better to have UI showing some information for the component to work is missing e.g 

```tsx
<h3>Missing patient information</h3>
```

2024-07-03 08:27 UTC, munania reviewed
UI FIXES DONE

2024-07-03 09:53 UTC, donaldkibet approved these changes

2024-07-03 09:53 UTC, donaldkibet commented on packages/esm-billing-app/src/billing-tabs/billling-tabs.component.tsx
> +            <Tab className={styles.tab}>{'All Bills'}</Tab>
```suggestion
            <Tab className={styles.tab}>{t('patientBills','Patient Bill')}</Tab>
```

2024-07-03 16:12 UTC, donaldkibet approved these changes
Thanks @munania LGTM 🤝, just do a follow up in the last suggestion.

2024-07-03 16:12 UTC, donaldkibet commented on packages/esm-billing-app/src/past-patient-bills/filtered-patient-bills.component.tsx
> +const PastPatientBills: React.FC<PatientBillsProps> = ({ patientUuid, bills, setPatientUuid }) => {
```suggestion
const PatientBills: React.FC<PatientBillsProps> = ({ patientUuid, bills, setPatientUuid }) => {
```

2024-07-03 16:12 UTC, merged