Community pharmacy
palladiumkenya/kenyaemr-esm-3.x pull request #262
Opened 2024-07-05 11:37 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Community Pharmacu UI that allows user to view their mapped pharmacies and view the patients and users mapped to the pharmacies.Allowes priviledged users to map users and patients to the pharamacies

## Screenshots
![image](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/98098891/23d27424-2638-43af-bb7b-07b7601160aa)
![image](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/98098891/d41bf9bd-9977-433b-8bae-1b1088a16877)
![image](https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/98098891/fb1d21bb-0e79-4583-aa2e-15557c67f1a7)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-07-06 20:35 UTC, donaldkibet requested changes
Thanks @Omoshlawi Great work here 🚀 , left some suggestion.

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/README.md
> +This is a frontend module that provides billing functionality.
Rename this with the correct description for community pharmacy

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/config-schema.ts
> +
Seems we aren't using any of these configs, we should remove this

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/hooks/index.ts
> +export { default as usePharmacy } from './usePharmacy';
Could we better rename these hooks quite hard to tell the difference

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/hooks/usePharmacies.ts
> +// TODO Custome representation optimization
nit: typo

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/hooks/usePharmacyPatients.ts
> +  const { data, isLoading, error } = useSWR<FetchResponse<PharamacyPatientMapping[]>>(url, fetchPharmacyPatients);
```suggestion
  const { data, isLoading, error } = useSWR<FetchResponse<Array<PharamacyPatientMapping>>>(url, fetchPharmacyPatients);
```
for code uniformity

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/index.ts
> +  () => import('./pharamacy-forms/delete-confirm-dialog.component'),
```suggestion
  () => import('./pharamacy-forms/delete-confirm-dialog.modal'),
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-component/pharmacy.component.tsx
> +      {/* <PharmacyMetrics /> */}
```suggestion

```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-detail-header/pharmacy-detail-header.component.tsx
> +        {/* <PharmacyIllustration /> */}
```suggestion
   
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +/* eslint-disable no-console */
```suggestion
/* eslint-disable no-console */
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +          // onClick={() => setIsModalOpen(true)}
```suggestion
      
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +            marginBottom: '1rem',
```suggestion
            marginBottom: '1rem',
```

should we extract this to the css file

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +          id="text-input-1"
```suggestion
          id="middleName"
```
have the ids upto date and if possible should we also have the placeholders translated?

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +                console.log('the state has changed');
```suggestion
                
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +              'Not Married',
should store these values in a variable instead of hard coding it directly here

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics-header.component.tsx
> +              console.log(e);
Does this control update the values?

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-metrics/pharmacy-metrics.component.tsx
> +        /> */}
```suggestion
      
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-tables/pharmacy-patients.component.tsx
> +                  onClose: () => dispose(),
should extract this logic to a function and just invoke it e.g 

```tsx
onClick={() => launchDeleteModal(patient.uuid)}
```

```tsx
const launchDeleteModal = (patientUuid: string) = >{
  const dispose = showModal('pharmacy-delete-confirm-dialog', {
    onDelete: () = >{
      handleRevoke(patient.uuid);
      dispose();
    },
    onClose: () = >dispose()
  }

```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-tables/pharmacy-table.component.tsx
> +          </Button> */}
```suggestion
       
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-tables/pharmacy-table.component.tsx
> +        </Button> */}
```suggestion
       
```

2024-07-06 20:35 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/pharmacy-tables/pharmacy-tables.scss
> +}
just confirm it doesn't affect other carbon table styling

2024-07-08 08:11 UTC, ojwanganto commented
Thanks, @Omoshlawi. Over to you @donaldkibet and @makombe for further reviews.

2024-07-08 08:48 UTC, donaldkibet approved these changes
Thanks @Omoshlawi

2024-07-08 08:48 UTC, donaldkibet commented on packages/esm-pharmacy-app/src/config-schema.ts
> +
Please remove this default configs

2024-07-08 08:53 UTC, donaldkibet commented
@Omoshlawi merging this in, please do a follow up to clean it up. Thanks!

2024-07-08 08:53 UTC, merged