(feat) added a UI for the showing prices
palladiumkenya/kenyaemr-esm-3.x pull request #273
Opened 2024-07-12 22:15 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

-  added  UI to support procedure, lab and radiology prices on the order basket

## Screenshots
example of procedure
![procedure](https://github.com/user-attachments/assets/c65e63d9-fb2c-4f35-9575-7c0491bdd998)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-07-13 12:27 UTC, donaldkibet requested changes

2024-07-13 12:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/lab-oder.scss
> +@import '@openmrs/esm-styleguide/src/vars';
```suggestion

```

2024-07-13 12:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/lab-order.component.tsx
> +      />
```suggestion
      <InlineLoading status="active" iconDescription="Loading" description="Loading data..." />
```

2024-07-13 12:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/lab-order.component.tsx
> +          A
```suggestion
          
```

2024-07-15 05:55 UTC, ojwanganto commented
@its-kios09 - please address the comments

2024-07-16 09:00 UTC, its-kios09 commented
> @its-kios09 - please address the comments

I have already address them

2024-07-16 09:07 UTC, makombe commented
@its-kios09 Address the failing lint issues. Thanks

2024-07-16 13:19 UTC, its-kios09 commented
> @its-kios09 Address the failing lint issues. Also, can you update the video to reflect the current status. Thanks



> @its-kios09 Address the failing lint issues. Also, can you update the video to reflect the current status. Thanks



> @its-kios09 Address the failing lint issues. Also, can you update the video to reflect the current status. Thanks

I have clean it

2024-07-17 16:38 UTC, makombe approved these changes
LTGM. Thanks @its-kios09

2024-07-17 16:40 UTC, merged