Feat: Added bill manager
palladiumkenya/kenyaemr-esm-3.x pull request #277
Opened 2024-07-17 13:18 UTC by amosmachora

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
In this PR I have replaced the bill waiver page with a more generic bill manager which allows for **waive**, **edit**, **cancel**, and delete operations on individual line items and also on the bill. I have also added a lot of UI improvements to correctly show loading screeens and data to provide more informative feedback to the user.

I have unfortunately not added tests yet _ (Majorly because i don`t know how to write tests in jest lol)_ but i will learn and provide more comprehensive PRs as we continue.

Also currently the only functionality that is calling the backend APIS is ** waive**. I will update the remaining three as soon as the backend apis are ready. 

I have also fixed a slight UI issue that the sidenav did not show the active status correctly.

All feedback will be highly appreciated.

## Screenshots
https://github.com/user-attachments/assets/bcdc3561-1e8a-48bb-a8b2-477585507f59

![image](https://github.com/user-attachments/assets/fb2d6fb9-a526-47ee-bfc5-0724b9d195a1)
![image](https://github.com/user-attachments/assets/a50f0381-885b-4512-aea5-93341d1ec90b)
![image](https://github.com/user-attachments/assets/9da77386-8b68-44fd-b689-e8b13922741b)
![image](https://github.com/user-attachments/assets/ac37ad8d-127a-49db-84ff-9671b366c0ba)
![image](https://github.com/user-attachments/assets/6e44944a-dcdc-4eb6-b4f9-7ed1bf468162)

## Related Issue

*None.*

## Other

*None.*

2024-07-17 21:01 UTC, ojwanganto commented
Thanks, @amosmachora. This is a real change. Tagging @makombe and @donaldkibet for their reviews.
One thing though, when editing bills, we can potentially allow only the quantity to be edited since prices are preconfigured. Thoughts?

2024-07-18 04:44 UTC, amosmachora commented
I am not the best person to be able to answer the specifics of what may or may not be edited but whatever you guys decide just inform me I'll be on it as soon as.

What I created was just of the top of my head.

2024-07-22 19:24 UTC, donaldkibet requested changes

2024-07-22 19:24 UTC, donaldkibet commented on package.json
> +    "@openmrs/esm-framework": "^5.6.1-pre.2065",
```suggestion
    "@openmrs/esm-framework": "next",
```

2024-07-22 19:24 UTC, donaldkibet commented on package.json
> +    "openmrs": "^5.6.1-pre.2065",
```suggestion
    "openmrs": "next",
```

2024-07-22 19:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/bill-line-items.component.tsx
> +      workspaceTitle: 'Edit Bill Form',
```suggestion
      workspaceTitle: t('editBillForm' , 'Edit Bill Form'),
```

2024-07-22 19:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/cancel-bill.modal.tsx
> +        Cancel bill
Have translation for these labels

2024-07-22 19:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/cancel-bill.scss
> +  padding-inline-end: calc(20% - 3rem);
we should be using carbon typography here e.g 

```scss
  @include type.type-style("heading-compact-02");
  ```

2024-07-22 19:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/patient-bills.component.tsx
> +      </div>
we should use empty state from `@openmrs/esm-framework`

2024-07-22 19:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          <UserHasAccess privilege="coreapps.systemAdministration">
This is hard cording this such that only system admin will see this. We need to define roles and privileges and assign them accordingly cc @ojwanganto @makombe thoughts?

2024-07-22 19:24 UTC, donaldkibet commented
Seems the build is also failing @amosmachora

2024-07-23 04:41 UTC, amosmachora commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/cancel-bill.scss
> +  padding-inline-end: calc(20% - 3rem);
ooh i see. Will work on this.

2024-07-23 04:45 UTC, amosmachora commented
Thanks for your feedback @donaldkibet will work on this. Im understanding this project a bit more each day : ) . Well received though. I had a question though about translations. From the community I have come to gather _(I might be very wrong about this)_ translations are a feature to allow for multi lingual support, but in our code we tend to translate from English to English which I don`t understand. Mind helping me undertand.

2024-07-23 05:33 UTC, donaldkibet commented
@amosmachora, we're not translating from English to English. The keys should be in English by default, for example:

```tsx
const { t } = useTranslation()
<h2>{t('billManager', 'Bill manager')}</h2>
```

Transifex will handle translation into different languages. English is sufficient for our needs, but we're translating hard-coded values to comply with community standards and conventions in OpenMRS 3.x.

2024-07-23 07:01 UTC, amosmachora commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/cancel-bill.modal.tsx
> +        Cancel bill
got it.

2024-07-23 07:13 UTC, amosmachora commented on packages/esm-billing-app/src/billable-services/bill-manager/patient-bills.component.tsx
> +      </div>
got it.

2024-07-23 07:13 UTC, amosmachora commented
@donaldkibet okay. I see it now. Thanks for clarifying.

2024-07-23 15:01 UTC, amosmachora commented on package.json
> +    "@openmrs/esm-framework": "^5.6.1-pre.2065",
Hi @donaldkibet this change seems to have broken the E2E tests. Please advice. 
![image](https://github.com/user-attachments/assets/d6b43119-24fc-40fb-b627-069ceba7b37f)

2024-07-23 17:16 UTC, ojwanganto commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          <UserHasAccess privilege="coreapps.systemAdministration">
@donaldkibet @makombe - you know you are more experienced here. Please guide him so that this is closed soonest.
Thanks :)

2024-07-24 20:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          <UserHasAccess privilege="coreapps.systemAdministration">
We should use the privileges on extension to configure privileges for this component. We can merge the PR and add a ticket to address access for it

2024-07-24 20:32 UTC, ojwanganto commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          <UserHasAccess privilege="coreapps.systemAdministration">
Thanks, @donaldkibet. Could you kindly provide a github link of where a similar piece has been implemented?

2024-07-25 05:38 UTC, amosmachora commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          <UserHasAccess privilege="coreapps.systemAdministration">
In that code I just assumed the person who wrote it knew what he was doing so I just left it there : )

2024-07-29 04:09 UTC, donaldkibet approved these changes

2024-07-29 04:09 UTC, merged