Added kenyaemr providers esm
palladiumkenya/kenyaemr-esm-3.x pull request #289
Opened 2024-07-29 07:30 UTC by Rugute

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Added Providers ESM

## Screenshots
<img width="1512" alt="Screenshot 2024-07-24 at 12 13 59" src="https://github.com/user-attachments/assets/f67a34f2-4f88-41bf-8daa-feb344ebeb10">

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-07-29 08:21 UTC, donaldkibet requested changes
Thanks @Rugute for this great work. Left some suggestions

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tables/providers-active.component.tsx
> +  const AdmissionWorkListEntries = [
extract this to a mock file or resource

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tables/providers-active.component.tsx
> +  const pageSizes = [10, 20, 30, 40, 50];
We should use `usePaginationInfo` hook for this.

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tables/providers-active.component.tsx
> +  const { goTo, results: paginatedResults, currentPage } = usePagination(searchResults, currentPageSize);
If we could leverage backend for this that would be great

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tables/providers-active.component.tsx
> +  return isLoading ? (
if we could use guard clause here e.g

```tsx
if (error) {
  return <EmptyState />;
}

if (isLoading) {
  return <DataTableSkeleton />;
}

return <div></div>; // actual logic for the table here
```

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tables/providers-discharged.component.tsx
> +    { id: 0, header: t('id', 'IDENTIFIER'), key: 'id' },
```suggestion
    {  header: t('id', 'IDENTIFIER'), key: 'id' },
```

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/api/api.ts
> +export const BASE_URL = '/ws/rest/v1/provider?v=full';
```suggestion
const providerUrl = `${restBaseUrl}/provider?v=full`
```
i don't think we need to export this constant since its a simple one linear to define it e.g

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/api/api.ts
> +  '/ws/rest/v1/provider?&v=custom:(uuid,identifier,display,person:(uuid,display),attributes:(uuid,display),retired)';
```suggestion
export const custom = custom:(uuid,identifier,display,person:(uuid,display),attributes:(uuid,display),retired)';
```

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/api/api.ts
> +};
no need to define this fetcher if we are hitting `openmrs` endpoints `openmrsfetch` will just work fine

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-metrics/providers-card.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
use as pointed above

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-metrics/providers-metrics-header.component.tsx
> +/* eslint-disable no-console */
```suggestion
```

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-metrics/providers-metrics.component.tsx
> +  const { response } = getAllProviders();
we should use `useSWRImmutable` to cache this aggressively since this data doesn't change very often

2024-07-29 08:21 UTC, donaldkibet commented on packages/esm-providers-app/src/providers-tabs/providers-tabs.scss
> +    outline: 2px solid var(--brand-03) !important;
Why are using `!important` here

2024-07-29 08:33 UTC, Rugute commented
I am working on the changes. Pushing it back shotly

2024-08-12 12:28 UTC, donaldkibet commented
Thanks @Rugute am closing this since i was unable to push some changes to the branch. I have migrated the changes to this PR. Feel appreciated for your work on this 🤝 
Opened PR https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/305

2024-08-12 12:28 UTC, closed without merging