Khp3 6325 filter out family relations in pns contacts leaving only sexual relationship
palladiumkenya/kenyaemr-esm-3.x pull request #299
Opened 2024-08-07 06:37 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
https://thepalladiumgroup.atlassian.net/browse/KHP3-6325

## Screenshots
![image](https://github.com/user-attachments/assets/8214f1e9-4632-44b9-ade4-0be54123b97c)
![Screenshot from 2024-08-07 09-36-16](https://github.com/user-attachments/assets/b5f07b09-0b62-47a3-bba8-e783fea72207)

## Related Issue

*None.*

## Other

*None.*

2024-08-07 07:16 UTC, donaldkibet requested changes
Thanks @Omoshlawi, seen changes on lab manifest yet the ticket indicates work on relationship. It would be good to separate the concern into two PRs. Thanks! 🍻

2024-08-07 07:16 UTC, donaldkibet commented on packages/esm-lab-manifest-app/src/forms/lab-manifest-form.workspace.tsx
> +        <span className={styles.sectionHeader}>Manifest Date range</span>
Lets just maintain the convention by having these as translated translation e.g
```tsx
t('manifestDateRange', 'Manifest Date range')
```

2024-08-07 07:16 UTC, donaldkibet commented on packages/esm-lab-manifest-app/src/header/lab-manifest-header.scss
> +  // gap: spacing.$spacing-05;
```suggestion
 
```

2024-08-07 07:16 UTC, donaldkibet commented on packages/esm-lab-manifest-app/src/tables/filter-table-header.component.tsx
> +        placeholder="Search this table"
translation

2024-08-07 07:40 UTC, Omoshlawi commented
@donaldkibet  , made 2 PRS for both 
Lab manifest: https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/297 , however it hasen't been merged, So I meged its branch locally tow work on this ticket branch since I needed some changes on it.

2024-08-08 12:32 UTC, donaldkibet approved these changes
Thanks @Omoshlawi LGTM

2024-08-08 12:32 UTC, merged