KHP3-6328 - Alignment of the Card Layout Header for Case Management Encounter Table
palladiumkenya/kenyaemr-esm-3.x pull request #300
Opened 2024-08-07 08:59 UTC by its-kios09

…state

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6328

## Screenshots
![case-Management-encounter](https://github.com/user-attachments/assets/320e4ec4-e380-4cbb-87fa-48a2ce1f6173)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-08-08 12:08 UTC, donaldkibet requested changes

2024-08-08 12:08 UTC, donaldkibet commented on package.json
> +    "@openmrs/esm-framework": "^5.7.3-pre.2161",
We should not be changing this version. We should only update `yarn.lock` file if we want to bump `@openmrs/esm-framework` version

2024-08-08 12:08 UTC, donaldkibet commented on package.json
> +    "openmrs": "^5.7.3-pre.2161",
Same as here

2024-08-08 12:08 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/encounters/case-encounter-header.scss
> +  height: 50% !important;
Can we achieve the height without `!important` not recommended to use it

2024-08-08 12:08 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/encounters/case-encounter-header.scss
> +  gap: 1rem;
```suggestion
  gap: layout.$spacing-05;
```

2024-08-08 12:08 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/encounters/case-encounter-header.scss
> +  gap: 1rem;
Lets leverage carbon spacing tokens as we move forward

2024-08-09 06:44 UTC, its-kios09 commented on package.json
> +    "@openmrs/esm-framework": "^5.7.3-pre.2161",
I will look at it

2024-08-09 06:44 UTC, its-kios09 commented on package.json
> +    "openmrs": "^5.7.3-pre.2161",
same i will rectifying it

2024-08-12 13:13 UTC, donaldkibet approved these changes
Thanks @its-kios09

2024-08-12 13:13 UTC, merged