KHP3-6329: Restore Card Header Layout in Billing History Table
palladiumkenya/kenyaemr-esm-3.x pull request #301
Opened 2024-08-07 09:40 UTC by its-kios09

…state

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6329

## Screenshots

*None.*

![billing-history](https://github.com/user-attachments/assets/a8ed0f0d-fb78-431e-bd75-f49c108a750a)

## Related Issue

*None.*

## Other

*None.*

2024-08-08 12:04 UTC, donaldkibet requested changes

2024-08-08 12:04 UTC, donaldkibet commented on packages/esm-billing-app/src/bill-history/bill-history.component.tsx
>        <>
Why don't we use the `EmptyState` component here since we need to show it here. Please provide a screenshot of the changes since it majorly UI we are addressing here

2024-08-08 12:07 UTC, ojwanganto commented
@its-kios09 - please provide this and we have this in

2024-08-12 13:12 UTC, donaldkibet approved these changes
Thanks @its-kios09

2024-08-12 13:12 UTC, merged