KHP3-6332: Update Notification and Behavior for Unconfigured Service Prices
palladiumkenya/kenyaemr-esm-3.x pull request #304
Opened 2024-08-08 21:35 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6332

## Screenshots

laboratory 
![LAB](https://github.com/user-attachments/assets/176eba0c-b2ae-44b9-9b4d-a4b47736720f)

Procedures
![procedure](https://github.com/user-attachments/assets/460f0e5c-196f-4f15-8eb6-06c46e4fdeaa)

Radiology
![RADIO](https://github.com/user-attachments/assets/a827c653-162b-4aac-9d46-89610ae7ee1a)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-08-09 04:04 UTC, donaldkibet requested changes

2024-08-09 04:04 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/imaging-order.component.tsx
> +  setHasPrice: (hasPrice: boolean) => void;
No need to have this side effect. We should check from the `PriceInfo` component whether it has a price configured for it. This is because we are already passing `billableItem` to the component.

Inside `PriceInfoOrder` component we should have this logic

```tsx
if(billableItem.servicePrices.length > 0){
   return <InlineNotification title="title" ...restOfProps/>
}
```

2024-08-17 11:31 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/imaging-order.component.tsx
> +  setHasPrice: (hasPrice: boolean) => void;
ping @its-kios09 left move this forward. Thanks!

2024-08-19 09:50 UTC, its-kios09 commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/imaging-order.component.tsx
> +  setHasPrice: (hasPrice: boolean) => void;
almost @donaldkibet

2024-08-19 17:48 UTC, donaldkibet approved these changes

2024-08-19 17:48 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/price-info-order.componet.tsx
> +            {billableItem.servicePrices.map((priceItem: any) => (
Lets just have the type for price here

2024-08-19 20:43 UTC, its-kios09 commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/price-info-order.componet.tsx
> +            {billableItem.servicePrices.map((priceItem: any) => (
sorted

2024-08-20 07:49 UTC, donaldkibet requested changes
Ping at @its-kios09 testing this its failing here. I don't think we need `setPrice` prop here
![Screenshot 2024-08-20 at 10 47 56](https://github.com/user-attachments/assets/4aa06fc8-ec04-41e0-86ee-d08f1c0bd682)

2024-08-20 12:04 UTC, donaldkibet approved these changes

2024-08-20 12:04 UTC, merged