Add SideNav Item Linking to ManageCommodityPrices component
palladiumkenya/kenyaemr-esm-3.x pull request #314
Opened 2024-08-14 14:19 UTC by 1wes

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

The added item enables privileged users to access a component through which they can edit the prices of non-pharm commodities. As it is, these commodities are billed at the buying price.

## Screenshots
![sideNavLinkItem](https://github.com/user-attachments/assets/751cf6d2-49a7-46fc-b0c3-4e6b2c712227)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-08-14 16:10 UTC, donaldkibet approved these changes
LGTM Thanks @1wes

2024-08-14 16:10 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          </UserHasAccess>
Not to be done now, but we should make this extension to be able to use `Display condition` to dynamically configure access level for this component.

2024-08-14 16:11 UTC, donaldkibet requested changes
Check the failing CI

2024-08-14 18:57 UTC, 1wes commented on packages/esm-billing-app/src/billable-services/billable-services-sidenav.component.tsx
> +          </UserHasAccess>
Alright. Will work on that.

2024-08-14 19:40 UTC, 1wes commented
> Check the failing CI

@donaldkibet, I have made the requested changes. Please review.

2024-08-15 07:39 UTC, donaldkibet approved these changes
Kindly update the translation, sorry for having not flagged this earlier.

2024-08-15 07:39 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/manage-commodity-price/manage-commodity-price.component.tsx
> +          <Tab>{'Search'}</Tab>
```suggestion
          <Tab>{t('search','Search')}</Tab>
```

2024-08-15 10:30 UTC, 1wes commented
@donaldkibet, I have corrected the linting errors on the search translation. Please check

2024-08-15 11:29 UTC, 1wes commented
@donaldkibet  Sorry, had forgotten to push the corresponding translations object. Please check

2024-08-15 18:37 UTC, donaldkibet approved these changes

2024-08-15 18:37 UTC, merged