Feat: Added PreAuth request UI
palladiumkenya/kenyaemr-esm-3.x pull request #316
Opened 2024-08-14 21:53 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

This user interface fetches outstanding invoice items and automatically fills out forms based on current visits. 

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

![preauth](https://github.com/user-attachments/assets/421a7399-1ba0-412f-9ac8-a76e4c0c9b56)

2024-08-15 18:46 UTC, donaldkibet commented
Could we have this work for HIE hidden under a feature flag see https://o3-docs.openmrs.org/docs/feature-flags

2024-08-16 11:54 UTC, its-kios09 commented
> Could we have this work for HIE hidden under a feature flag see https://o3-docs.openmrs.org/docs/feature-flags

Okay sure let me update it

2024-08-17 11:51 UTC, donaldkibet reviewed
I've done a preliminary review. Overall LGTM. I'd recommend a more thorough review before final approval. Thank you for your work on this. cc @ojwanganto @makombe @Omoshlawi

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +  }, [confirmedDiagnoses, recentVisit, mflCodeValue, setValue]);
Have we tried setting these values using react-hook-form `defaultValues`

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@use '@carbon/styles/scss/spacing';
```suggestion
@use '@carbon/layout';
```

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@use '@carbon/styles/scss/type';
```suggestion
@use '@carbon/type';
```

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
are we using this anywhere. if possible lets stick with carbon tokens

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/pre-auth-dashboard.component.tsx
> +// src/components/PreAuthRequestDashboard.tsx
```suggestion

```

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/table/pre-auth-table.component.tsx
> +    { header: 'Serial No.', key: 'serialno' },
should we have these headers translated. Just to have consistency within the packages

2024-08-17 11:51 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/table/pre-auth-table.component.tsx
> +  const processBillItem = (item) => (item.item || item.billableService)?.split(':')[1];
cc @ojwanganto @makombe we should not be doing this on the frontend. We need to have billable service name displayed correctly. Alternatively we can have it as an object
```json
{
  "billableService": {
    "uuid": "some-uuid",
    "display": "Some billable service"
  }
}
```

2024-08-18 11:11 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/table/pre-auth-table.component.tsx
> +    { header: 'Serial No.', key: 'serialno' },
Sorted

2024-08-18 11:11 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/pre-auth-dashboard.component.tsx
> +// src/components/PreAuthRequestDashboard.tsx
removed

2024-08-18 11:11 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
sorted

2024-08-18 11:12 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@use '@carbon/styles/scss/type';
sorted

2024-08-18 11:12 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +@use '@carbon/styles/scss/spacing';
sorted

2024-08-18 21:51 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +  }, [confirmedDiagnoses, recentVisit, mflCodeValue, setValue]);
Yes, the `default values`  in react-hook-form sets the initial default values for the form fields when you initialize the form with useForm. Or what do you think is the better approach I would appreciate your opinion

2024-08-19 04:54 UTC, donaldkibet commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +  }, [confirmedDiagnoses, recentVisit, mflCodeValue, setValue]);
This `useEffect` will force a re-render. Its best to initialize the form fields using react hook `useForm` this way we do not have a side effect

2024-08-19 05:04 UTC, donaldkibet requested changes
Since we're implementing multiple feature flags (e.g., pre-auth, claim management, benefits package) that all serve the same purpose of pausing HIE work, let's consolidate them into a single flag for easier management and smoother transitions.

2024-08-19 05:05 UTC, donaldkibet commented
@its-kios09 one final bit, lets have the pre-auth form as workspace item. Ted should update the designs to follow conventions

2024-08-19 13:47 UTC, its-kios09 commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +  }, [confirmedDiagnoses, recentVisit, mflCodeValue, setValue]);
i will do a follow up PR we sort it

2024-08-19 16:46 UTC, its-kios09 commented
> @its-kios09 one final bit, lets have the pre-auth form as workspace item. Ted should update the designs to follow conventions

@donaldkibet I was thinking the design I can do a follow up PR

2024-08-19 17:53 UTC, donaldkibet approved these changes

2024-08-20 12:50 UTC, donaldkibet commented
Please resolve the conflicts

2024-08-20 19:28 UTC, donaldkibet commented
Should this form be hidden behind a feature flag. If yes please hide it then we merge it in

2024-08-20 19:29 UTC, donaldkibet submitted a review, later dismissed

2024-08-21 08:43 UTC, its-kios09 commented
> Should this form be hidden behind a feature flag. If yes please hide it then we merge it in

@donaldkibet  I have added the HIE flags

2024-08-21 09:19 UTC, makombe reviewed
Generally looks good. Thanks @its-kios09

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +        subtitle: t('sendClaim', 'Pre Authorization request sent successfully'),
```suggestion
        subtitle: t('sendClaim', 'Pre authorization request sent successfully'),
```

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.component.tsx
> +        subtitle: t('sendClaimError', 'Pre Authorization request failed, Please try later'),
```suggestion
        subtitle: t('sendClaimError', 'Pre authorization request failed, please try later'),
```

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +    padding: 0rem;
```suggestion
    padding: 0;
```

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/form/pre-auth-form.scss
> +  padding: 0rem;
```suggestion
  padding: 0;
```

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/pre-auth-dashboard.scss
> +  padding: 0 1rem;
we can consistently use carbon layouts

2024-08-21 09:19 UTC, makombe commented on packages/esm-billing-app/src/claims/pre-auth/table/pre-auth-table.component.tsx
> +                {t('noMatchingItemsToDisplay', 'No matching items to display')}
Maybe here we can leverage on the empty state from community provided out of the box.

2024-08-21 16:27 UTC, its-kios09 commented
@makombe  Thanks for the suggestion

2024-08-27 20:23 UTC, donaldkibet approved these changes

2024-10-15 10:05 UTC, donaldkibet commented
cc @its-kios09 merge conflicts

2024-10-15 12:41 UTC, ojwanganto commented
I hope we still have this under a feature flag.

2024-10-15 19:14 UTC, its-kios09 commented
@donaldkibet I have sorted out the conflicts

2024-10-16 07:56 UTC, merged