Khp3 6347 add an shr summary pannel
palladiumkenya/kenyaemr-esm-3.x pull request #317
Opened 2024-08-15 09:24 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Added OTP Authorization before pulling SHR Records (emulated using alert i.e not sending sms yet)
- Moved SHR summary components from billing esm to shr esm

## Screenshots

https://github.com/user-attachments/assets/45e0570e-74e7-4257-a97c-8f9ac6c04f63

## Related Issue

*None.*

## Other

*None.*

2024-08-17 11:36 UTC, donaldkibet commented on packages/esm-shr-app/src/hooks/visits.json
> +{
Should we have this in a mock some where

2024-08-19 07:46 UTC, Omoshlawi commented on packages/esm-shr-app/src/hooks/visits.json
> +{
Like where? @donaldkibet

2024-08-19 18:39 UTC, donaldkibet requested changes
Thanks @Omoshlawi 💪🏽

2024-08-19 18:39 UTC, donaldkibet commented on packages/esm-shr-app/src/index.ts
> +  registerFeatureFlag('shr-summary', 'SHR Summary', 'Adds authorization to pull a ptient SHR information');
Lets have one single source of truth for SHR work could we use this flag https://github.com/palladiumkenya/kenyaemr-esm-3.x/blob/9b5082f205c923ee07c5b48af2ea10de7f3f7cb4/packages/esm-billing-app/src/index.ts

2024-08-19 18:39 UTC, donaldkibet commented on packages/esm-shr-app/src/index.ts
> +  : undefined;
This isn't correct
```suggestion
export const shrSummaryDashboardLink = getSyncLifecycle(createDashboardLink({ ...shrSummaryDashboardMeta, moduleName }), options)
```

for this under routes.json we can have to toggle the feature flag
```json
{
      "name": "patient-chart-shr-summary-dashboard-link",
      "component": "shrSummaryDashboardLink",
      "slot": "patient-chart-dashboard-slot",
      "meta": {
        "columns": 1,
        "columnSpan": 1,
        "slot": "patient-chart-shr-summary-dashboard-slot",
        "path": "SHR Portal"
      },
      "featureFlag": "healthInformationExchange"
    },
```

2024-08-19 18:39 UTC, donaldkibet commented on packages/esm-shr-app/src/routes.json
> +      "name": "SHR Portal",
This is the place to have the feature flag for shr work.

2024-08-19 18:39 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/tables/shr-summary-table.component.tsx
> +const PatientSHRSummartTable: React.FC<PatientSHRSummartTableProps> = () => {
```suggestion
const PatientSHRSummaryTable: React.FC<PatientSHRSummartTableProps> = () => {
```

2024-08-19 18:39 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/tables/shr-summary-table.component.tsx
> +const PatientSHRSummartTable: React.FC<PatientSHRSummartTableProps> = () => {
There is also typo on the props

2024-08-20 07:43 UTC, donaldkibet commented
ping @Omoshlawi please resolve the conflict. Would like to conclude work on this today. Thanks!

2024-08-20 11:42 UTC, Omoshlawi commented
@donaldkibet  Done

2024-08-20 11:50 UTC, donaldkibet approved these changes

2024-08-20 11:50 UTC, donaldkibet commented on packages/esm-shr-app/src/hooks/usePatientIdentifiers.ts
> +const usePatientIdentifiers = (uuid: string) => {
using `usePatient` hook from `@openmrs/esm-framework` that returns a `fhir.Patient` object we should be able to retrieve the identifiers, there is no need for this additional request

2024-08-20 11:50 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/shr-summary.resource.ts
> +  var string = '0123456789';
```suggestion
  const string = '0123456789';
```

2024-08-20 11:50 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/shr-summary.resource.ts
> +  var string = '0123456789';
also good idea to have a more descriptive variable name here

2024-08-20 11:50 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/shr-summary.resource.ts
> +  var len = string.length;
Its recommended we don't use `var` for declaring variables. Please use either `let` or `const`

2024-08-20 11:50 UTC, donaldkibet commented on packages/esm-shr-app/src/shr-summary/shr-summary.resource.ts
> +const PHONE_NUMBER_REGEX = /^(\+?254|0)((7|1)\d{8})$/;
good to have these in a separate file named `constants`

2024-08-20 11:51 UTC, donaldkibet commented
Merging this, please address the comments in a follow up PR.

2024-08-20 11:52 UTC, merged