Fix: Added form to edit and delete billable service together with its prices
palladiumkenya/kenyaemr-esm-3.x pull request #319
Opened 2024-08-15 16:22 UTC by FelixKiprotich350

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Added form to edit and delete billable service together with its prices

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-08-15 18:45 UTC, donaldkibet commented
@FelixKiprotich350 please resolve the conflict and attach video of the changes.

2024-08-16 06:09 UTC, FelixKiprotich350 commented
@donaldkibet fixed

2024-08-17 11:24 UTC, donaldkibet requested changes
Thanks @FelixKiprotich350 left some suggestion

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/softDeleteBillableService.modal.tsx
> +export const SoftDeleteBillableServiceModal: React.FC<{
```suggestion
export const DeleteBillableServiceModal: React.FC<{
```

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/softDeleteBillableService.modal.tsx
> +  service: any;
lets have the appropriate type here.

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/softDeleteBillableService.modal.tsx
> +          subtitle: 'Service has been successfully deleted.',
Should we have this translated. Together with the error message

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bill-manager/modals/softDeleteBillableService.modal.tsx
> +          </div>
Lefts extract repeated logic to a `ServiceItemCard` component

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
> +  const url = `/ws/rest/v1/cashier/api/deletebillable-service`;
```suggestion
  const url = `${restBaseUrl}/cashier/api/deletebillable-service`;
```
this is a soft delete to have the complete delete we append the param `?purge=true`

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.component.tsx
> +const DEFAULT_PAYMENT_OPTION = { paymentMode: '', price: '1', uuid: null };
```suggestion
const DEFAULT_PAYMENT_OPTION = { paymentMode: '', price: '', uuid: null };
```

why have the default to 1 for price

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/add-billable-service.component.tsx
> +                  placeholder="Select service type"
Should this be translated

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/edit-billable-service.component.tsx
> +            // defaultValue={initialValues?.serviceTypeName || null}
```suggestion
           
```

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/edit-billable-service.component.tsx
> +                  value={(() => {
We can simplify this to 
```tsx
value={selectedConcept ? selectedConcept.display : (debouncedSearchTerm ? value : undefined)}
```

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/edit-billable-service.component.tsx
> +          {(() => {
Why are we using IIFE here. Would it be better to have the search and search results as an independent component.

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billing-breakdown/bills-table.component.tsx
> +  { id: 'PENDING', text: 'Pending bills' },
I think we have the enums for this payment status

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/billing.resource.ts
> +export const useInterventions = (searchString: string = '') => {
Why do we have HIE work here?

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
> +      { title: 'Insurance Covers', count: paidBills, extensionPage: 'insurancecovers' },
Having this goes beyond the scope of the PR. Its best to have these changes in a separate PR and agreed on designs.

2024-08-17 11:24 UTC, donaldkibet commented on packages/esm-billing-app/src/overlay/hook.ts
> +import { getGlobalStore } from '@openmrs/esm-framework';
We should be moving away from using the overlay to using the workspace system for this

2024-08-18 20:11 UTC, FelixKiprotich350 commented on packages/esm-billing-app/src/billable-services/billable-service.resource.tsx
> +  const url = `/ws/rest/v1/cashier/api/deletebillable-service`;
@donaldkibet the endpoint does not  exist am waiting for @makombe  to have this then i will finalize

2024-08-18 20:34 UTC, FelixKiprotich350 commented on packages/esm-billing-app/src/metrics-cards/metrics-cards.component.tsx
> +      { title: 'Insurance Covers', count: paidBills, extensionPage: 'insurancecovers' },
ok actually i havenot done anything , i can pull this out as i wait for the designs for that part

2024-08-18 20:36 UTC, FelixKiprotich350 commented on packages/esm-billing-app/src/billing.resource.ts
> +export const useInterventions = (searchString: string = '') => {
that was the discussion from jacinta and simon to have intervention selected and attached to the billing

2024-08-18 20:58 UTC, FelixKiprotich350 commented on packages/esm-billing-app/src/overlay/hook.ts
> +import { getGlobalStore } from '@openmrs/esm-framework';
ill make a follow up on this

2024-08-19 18:26 UTC, FelixKiprotich350 commented
@donaldkibet check on this

2024-08-19 18:34 UTC, donaldkibet reviewed
Thanks @FelixKiprotich350, some nice work. Please address the few suggestions. Please don't add any new features to this branch its quite big. Thanks for your work 💪🏽

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/hooks/debounce-hook.ts
> +export function useDebounce<Func extends SomeFunction>(func: Func, delay = 1000) {
we have `useDebounce` from `@openmrs/esm-framework` should leverage that

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/manage-commodity-price/stock-items-table.component.tsx
> +      // genericName: <EditStockItemActionsMenu data={items[index]} />,
```suggestion

```

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/manage-commodity-price/stock-items-table.component.tsx
> +              // stockItem.isDrug = !!stockItem.drugUuid;
```suggestion
             
```

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/manage-commodity-price/stock-items.resource.ts
> +// } from "../core/api/types/stockItem/StockItem";
```suggestion

```

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/root.scss
> +$button-primary: #0078a6;
All these colors are available under `@use `@cabon/colors`;

2024-08-19 18:34 UTC, donaldkibet commented on packages/esm-billing-app/src/root.scss
> +@use '@carbon/styles/scss/spacing';
Would want us to move away from the convention and just have styles for each component instead of having `root.scss`

2024-08-19 18:36 UTC, donaldkibet commented
cc @makombe @ojwanganto @amosmachora @its-kios09 @Omoshlawi please review the code. I might miss a thing or two. Thanks!

2024-08-20 07:38 UTC, donaldkibet approved these changes

2024-08-20 07:39 UTC, donaldkibet commented
Merging this in @RAJABIBRAZ @Murithijoshua @enyaencha @andrineM please take a look at this https://thepalladiumgroup.atlassian.net/browse/KHP3-6460 is the associated ticket

2024-08-20 07:40 UTC, merged

2024-08-20 08:45 UTC, Murithijoshua commented
@donaldkibet Thanks We are looking at