(fix) converted editing billable service form from overlay to workspace
palladiumkenya/kenyaemr-esm-3.x pull request #328
Opened 2024-08-20 23:49 UTC by FelixKiprotich350

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Converted editing billable service form from overlay to workspace

## Screenshots
[screen-capture (6).webm](https://github.com/user-attachments/assets/5a944ff2-395d-471c-8d60-11a685736763)

## Related Issue

*None.*

## Other

*None.*

2024-08-20 23:49 UTC, FelixKiprotich350 commented
hey @donaldkibet  and @ojwanganto check this workspace

2024-08-21 08:27 UTC, donaldkibet requested changes

2024-08-21 08:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
> +@import '~@openmrs/esm-styleguide/src/vars';
```suggestion

```
We don't need this import. All styles can be derived from respective carbon imports

2024-08-21 08:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
> +@use '@carbon/styles/scss/type';
```suggestion
@use '@carbon/layout';
@use '@carbon/type';
```

2024-08-21 08:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
> +  font-size: 14px;
we should the typography classes provided by carbon e.g

```scss
@include type.type-style('heading-01');
```
See https://carbondesignsystem.com/elements/typography/type-sets

2024-08-21 08:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
> +  grid-template-columns: 40% 30% 20%;
Are better of using carbon grid hee?

2024-08-21 08:27 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.scss
> +  margin-top: 1rem;
use carbon token for layout

2024-08-21 08:36 UTC, makombe reviewed
Thanks @FelixKiprotich350 generally looks good.

2024-08-21 08:36 UTC, makombe commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.workspace.tsx
> +                  placeholder="Enter service short name"
We should also translate the placeholder here

2024-08-21 08:36 UTC, makombe commented on packages/esm-billing-app/src/billable-services/create-edit/workspaces/edit-billable-service.workspace.tsx
> +          <FormLabel className={styles.subTitle}>Associated Concept</FormLabel>
Lets translate this as well

2024-08-21 16:23 UTC, FelixKiprotich350 commented
@makombe done

2024-08-21 16:23 UTC, FelixKiprotich350 commented
@makombe i have fixed the issue discussed earlier

2024-08-21 16:53 UTC, makombe approved these changes
Thanks @FelixKiprotich350

2024-08-21 16:54 UTC, merged

2024-08-21 17:36 UTC, ojwanganto commented
Thanks, @FelixKiprotich350 @donaldkibet @makombe