[KHP3-6476] Initial set up of health work registry
palladiumkenya/kenyaemr-esm-3.x pull request #332
Opened 2024-08-21 22:09 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots
![navbar](https://github.com/user-attachments/assets/b404ef21-cce9-41bd-b51b-feae43c0c8a5)

## Related Issue
see: https://thepalladiumgroup.atlassian.net/browse/KHP3-6476

## Other

*None.*

2024-08-21 22:11 UTC, its-kios09 commented
Updating the providers management by Rugut so far I have done the header and custom metrics

2024-08-22 09:29 UTC, ojwanganto commented
Looks good @its-kios09 and @Rugute. Are we keeping both tabs or we'll just remain with one?

2024-08-23 05:15 UTC, donaldkibet commented
@its-kios09 why do we have context switcher and tabs. Seem out of touch. There has been recent merge on the dashboard header component from the community https://github.com/openmrs/openmrs-esm-core/pull/1084

2024-08-23 05:23 UTC, donaldkibet requested changes

2024-08-23 05:23 UTC, donaldkibet commented on packages/esm-providers-app/src/component/providers.component.tsx
> +      {/* <ProvidersMetrics /> */}
```suggestion
     
```

2024-08-23 05:23 UTC, donaldkibet commented on packages/esm-providers-app/src/header/providers-header.component.tsx
> +        </div>
We should extract this to a component e.g MetricCard its repeated multiple times

```tsx
export const MetricCard: React.FC<MetricCardProps> = ({ label, value }) => {
  return (
    <div className={styles.wrapMetrics}>
      <span className={styles.metricLabel}>{label}</span>
      <span className={styles.metricValue}>value</span>
    </div>
  );
};
```

2024-08-23 05:23 UTC, donaldkibet commented on packages/esm-providers-app/src/header/providers-header.component.tsx
> +          <span className={styles.metricValue}>0</span>
should this value be computed?

2024-08-23 05:23 UTC, donaldkibet commented on packages/esm-providers-app/src/header/providers-header.scss
> +  background-color: $ui-02;
We should start using `@carbon/colors` import. Instead of `~@openmrs/esm-styleguide/src/vars`

2024-08-23 05:23 UTC, donaldkibet commented on packages/esm-providers-app/src/header/providers-header.scss
> +  font-family: IBMPlexSans;
This is wrong we should use carbon typography [typesets](https://carbondesignsystem.com/elements/typography/type-sets)

2024-08-23 07:17 UTC, makombe commented on packages/esm-providers-app/src/header/providers-header.component.tsx
> +          <p className={styles['page-name']}>{title}</p>
```suggestion
        <div className={styles.pageLabels}>
          <p className={styles.pageName}>{title}</p>
```

2024-08-23 07:17 UTC, makombe commented on packages/esm-providers-app/src/header/providers-header.scss
> +.page-name {
```suggestion
.pageName {
```

2024-08-23 07:17 UTC, makombe commented on packages/esm-providers-app/src/header/providers-header.scss
> +.left-justified-items {
```suggestion
.leftJustifiedItems {
```

2024-08-23 13:54 UTC, its-kios09 commented
@donaldkibet @makombe I will work on it

2024-08-23 13:57 UTC, its-kios09 commented
> Looks good @its-kios09 and @Rugute. Are we keeping both tabs or we'll just remain with one?

@ojwanganto I am cleaning up the UI as I upgrade it UI currently this is how it will look like 


https://github.com/user-attachments/assets/7db7a1b7-144e-4402-a139-b4bc617493b2

2024-08-23 14:01 UTC, its-kios09 commented on packages/esm-providers-app/src/component/providers.component.tsx
> +      {/* <ProvidersMetrics /> */}
removed

2024-08-23 14:03 UTC, its-kios09 commented on packages/esm-providers-app/src/header/providers-header.scss
> +  font-family: IBMPlexSans;
removed

2024-08-23 17:07 UTC, ojwanganto commented
Thanks, @its-kios09

2024-08-25 19:00 UTC, donaldkibet commented
cc @its-kios09 @patryllus needed this feature to merged in. Maybe we could fast track to have it merged EOD Monday. Thanks!

2024-08-26 05:19 UTC, its-kios09 commented on packages/esm-providers-app/src/header/providers-header.component.tsx
> +          <p className={styles['page-name']}>{title}</p>
resolved

2024-08-26 05:19 UTC, its-kios09 commented on packages/esm-providers-app/src/header/providers-header.scss
> +.left-justified-items {
resolved

2024-08-26 05:20 UTC, its-kios09 commented on packages/esm-providers-app/src/header/providers-header.scss
> +  background-color: $ui-02;
resolved

2024-08-26 05:32 UTC, donaldkibet approved these changes
Thanks @its-kios09

2024-08-26 05:32 UTC, donaldkibet commented on packages/esm-providers-app/src/api/api.ts
> +// import useSWR from 'swr';
We should just remove dead code

2024-08-26 05:32 UTC, donaldkibet commented on packages/esm-providers-app/src/header/providers-header.scss
> +.header__section__container {
we should stick with convention of using `camelCase` for scss class names this should be `.headerSectionContainer`

2024-08-26 05:32 UTC, donaldkibet commented on packages/esm-providers-app/src/workspace/hook/provider-form.resource.ts
> +  const allowedUuids = ['49af6cdc-7968-4abb-bf46-de10d7f4859f', 'be9beef6-aacc-4e1f-ac4e-5babeaa1e303'];
We should have these uuids stored either in a config or constant file. we can also try have a more descriptive name e.g `allowedIdentifierTypeUuids`

2024-08-26 05:33 UTC, merged