Alert message to notify provider on Reg Licence expired date
palladiumkenya/kenyaemr-esm-3.x pull request #339
Opened 2024-08-26 17:17 UTC by gabriel090

Your Licence Number will be expiring on {Date}  Once expired any services offered may not be claimed from SHA

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

https://github.com/user-attachments/assets/07235319-6401-477f-8ea1-92e1df2fc484

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-08-27 10:41 UTC, donaldkibet requested changes

2024-08-27 10:41 UTC, donaldkibet commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +  }, []);
This seems like it will only run once durning the first component mount. Seen from the video you need to refresh for the data to be available.

2024-08-27 10:41 UTC, donaldkibet commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +    : '';
```suggestion
 const formattedExpiryDate = licenseExpiryDate
    ? dayjs(licenseExpiryDate).format('YYYY-MM-DD')
    : '';
```

2024-08-27 10:41 UTC, donaldkibet commented on packages/esm-providers-app/src/provider-alert-message/popup-banner.component.tsx
> +            Your Licence Number will be expiring on <strong>{expiryDate}</strong>. Once expired, any services offered
Translate this hard coded string

2024-08-27 10:42 UTC, donaldkibet commented
Also resolve the conflicts

2024-08-27 20:22 UTC, donaldkibet commented
cc @gabriel090 lets move this forward. Thanks!

2024-08-30 10:11 UTC, gabriel090 commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +  }, []);
fixed. Thanks

2024-08-30 10:11 UTC, gabriel090 commented on packages/esm-providers-app/src/provider-alert-message/popup-banner.component.tsx
> +            Your Licence Number will be expiring on <strong>{expiryDate}</strong>. Once expired, any services offered
worked on this

2024-08-30 11:48 UTC, makombe reviewed
Thanks @gabriel090 I have dropped some suggestions

2024-08-30 11:48 UTC, makombe commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +      const formattedDate = licenseExpiryDate ? dayjs(licenseExpiryDate).format('YYYY-MM-DD') : '';
Use `formatDate` provided to handle date formats

2024-08-30 11:48 UTC, makombe commented on packages/esm-providers-app/src/provider-alert-message/popup-banner.component.tsx
> +const PopupBanner: React.FC<PopupBannerProps> = ({ expiryDate }) => {
We can also name this function appropriately instead of just calling PopupBanner

2024-08-30 11:48 UTC, makombe commented on packages/esm-providers-app/src/types/index.ts
> +  sessionLocation: any;
This should be properly typed. Avoid using the type any

2024-08-30 11:49 UTC, makombe commented
Also, resolve the conflicts

2024-09-18 05:59 UTC, StanleyMasinde commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +    : '';
### Sorry for the potential Spam

How about using `Intl.DatetimeFormat()`

<img width="364" alt="image" src="https://github.com/user-attachments/assets/b3ae2f23-88d6-4673-8e59-b8b93af75eba”>
<img width="364" alt="image" src="https://github.com/user-attachments/assets/82dd57ff-306d-4d55-af6d-c784e8cc4ad7">


If you leave the locale blank, it will use the user’s locale and formatting settings and this is the best option IMO. The user will see a date format that their system already uses.

2024-10-04 19:05 UTC, donaldkibet commented
cc @gabriel090 please have a look at this

2024-10-07 05:56 UTC, donaldkibet commented
ping @gabriel090 please lets have the conflicts merged

2024-10-07 07:48 UTC, gabriel090 commented
Working on it

On Mon, Oct 7, 2024, 8:57 AM Donald Kibet ***@***.***> wrote:

> ping @gabriel090 <https://github.com/gabriel090> please lets have the
> conflicts merged
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/palladiumkenya/kenyaemr-esm-3.x/pull/339#issuecomment-2395970451>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB5TVQODDGYPZR2H4A6NRJDZ2IPEBAVCNFSM6AAAAABNENY74CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVHE3TANBVGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-07 14:09 UTC, gabriel090 commented on packages/esm-providers-app/src/provider-alert-message/provider-alert-message.component.tsx
> +      const formattedDate = licenseExpiryDate ? dayjs(licenseExpiryDate).format('YYYY-MM-DD') : '';
Thanks fixed

2024-10-07 14:16 UTC, gabriel090 commented on packages/esm-providers-app/src/provider-alert-message/popup-banner.component.tsx
> +const PopupBanner: React.FC<PopupBannerProps> = ({ expiryDate }) => {
I have renamed it as AlertMessageBanner

2024-10-08 06:29 UTC, closed without merging