KHP3-6497: Rename Key population to key and vulnerable population
palladiumkenya/kenyaemr-esm-3.x pull request #364
Opened 2024-09-18 20:59 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

![KeyP](https://github.com/user-attachments/assets/9839ab03-9bfc-4e67-96ff-38d45a49efd6)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-09-19 05:11 UTC, makombe requested changes

2024-09-19 05:11 UTC, makombe commented on packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
> +
@its-kios09 I doubt if this check will work. We had renamed the program name from backend to be `KVP`

2024-09-19 05:12 UTC, makombe commented on packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
> +
Build the latest module for kenyakeypop and test again

2024-10-04 08:53 UTC, donaldkibet commented on packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
> +
@its-kios09 any update on this PR

2024-10-09 09:55 UTC, donaldkibet commented
@makombe mind giving this another quick review

2024-10-11 08:40 UTC, its-kios09 commented on packages/esm-care-panel-app/src/care-programs/care-programs.component.tsx
> +
@donaldkibet  Nop i believed it was sorted on the backend

2024-10-11 08:40 UTC, its-kios09 commented
> @makombe mind giving this another quick review

@donaldkibet  forgot to give an update it was sorted by makombe can I close the PR?

2024-10-11 08:45 UTC, makombe commented
@its-kios09 I think we should close this as it had been sorted at the metadata level. Thanks

2024-10-11 08:45 UTC, closed without merging

2024-10-11 08:47 UTC, makombe commented
For reference purposes https://github.com/palladiumkenya/openmrs-module-kenyakeypop/pull/206