feat: bulk upload billable services
palladiumkenya/kenyaemr-esm-3.x pull request #366
Opened 2024-09-24 18:22 UTC by amosmachora

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR adds a feature to bulk upload billable services based on a template. The essense of this feature is to make migration to 3.x as seamless as possible. This feature came up as a requirement as discussions to move loitokitok district hospital to 3.x matured.

The functionality is simple the app takes in an excel file based on a template that will be provided. It then successfully uploads the new billable services. If any of the billable services fail to be uploaded a new excel file is generated and downloaded on the users client for further correction then the process is repeated.

## Screenshots
### Video
https://github.com/user-attachments/assets/70516f04-8b53-420e-aebd-0dd85f5182d2

## Related Issue

*None.*

## Other

*None.*

2024-09-25 11:46 UTC, donaldkibet commented
Thanks @amosmachora could we have the upload button next to the actions button. This is just to follow the carbon design of where we have buttons on table table tool bar

2024-09-25 11:48 UTC, donaldkibet commented
We should also disable the upload button while the upload is still in progress

2024-09-25 15:57 UTC, amosmachora commented
made the necessary changes @donaldkibet

2024-10-02 06:56 UTC, donaldkibet requested changes

2024-10-02 06:56 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billables/form-helper.ts
> +};
This should be in the types file

2024-10-02 06:56 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billables/form-helper.ts
> +  currentlyExistingBillableServices: ChargeAble[],
```suggestion
  currentlyExistingBillableServices: Array<ChargeAble>,
```

2024-10-02 06:56 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billables/form-helper.ts
> +  const firstSheetName = workbook.SheetNames[0];
Are there scenarios the worksheet would have more than one worksheet. We should support

2024-10-02 06:56 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bulk-import-billable-service.component.tsx
> +export const BulkImportBillableServices = ({ closeModal }) => {
If this is a modal, we should follow the naming convention

2024-10-02 06:56 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/bulk-import-billable-service.component.tsx
> +      if (file.size > 2097152) {
we should extract the file size to a constant to avoid the magic number here

e.g

```ts
// Size in MegaBits
const MAX_ALLOWED_FILE_SIZE = 2097152
```

2024-10-04 08:41 UTC, amosmachora commented
Made all the necessarry changes @donaldkibet .

2024-10-04 19:07 UTC, donaldkibet approved these changes
Thanks @amosmachora please lets have the conflcts resolve to merge this in

2024-10-07 11:12 UTC, donaldkibet commented
@amosmachora i think it would also be great to include a template that users can download and later use that for bulk uploading

2024-10-07 11:57 UTC, donaldkibet commented
cc @amosmachora  kindly assit resolve the conlicts

2024-10-07 12:01 UTC, amosmachora commented
> it would also be great to include a template that

I thought so too but technically I didn`t know how to approach this. Before what I have done is I have included the template file in the source code for the repo then the user could download from there but that approach never felt right. Maybe you could help me figure out the technicalities of sotring the template then I will add the feature.

2024-10-07 17:05 UTC, donaldkibet approved these changes

2024-10-07 17:05 UTC, merged