Shr new data tables
palladiumkenya/kenyaemr-esm-3.x pull request #37
Opened 2023-09-21 05:13 UTC by PatrickWaweru

## Requirements

- [ X] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ X] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ X] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

## Related Issue

*None.*

## Other

*None.*

2023-09-21 13:47 UTC, donaldkibet requested changes
Thanks @PatrickWaweru left some suggestions

2023-09-21 13:47 UTC, donaldkibet commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +  data: itemDetails[];
Preferred syntax is 
```suggestion
  data: Array<ItemDetails>
```
Its nit just to keep things consistent across repos

2023-09-21 13:47 UTC, donaldkibet commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +  const tableHeaders = ['Allergen', 'Reaction', 'Severity', 'Onset Date', 'Date Recorded'];
```suggestion
  const tableHeaders = [{key:'allergen', t('allergen','Allergen')}];
```
the `t` function is to provide translation and carbon definition of headers should have the key and header values [see](https://react.carbondesignsystem.com/?path=/docs/components-datatable-basic--overview)

2023-09-21 13:47 UTC, donaldkibet commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +            </TableBody>
``` js
<TableBody>
        {rows.map((row) => (
          <TableRow {...getRowProps({ row })}>
            {row.cells.map((cell) => (
              <TableCell key={cell.id}>{cell.value}</TableCell>
            ))}
          </TableRow>
        ))}
      </TableBody>
```

This is just to keep in line with how carbon implements data-table

2023-09-21 13:47 UTC, donaldkibet commented on packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
> +import SHRMedicationsDataTable from './shrMedicationsDataTable.component';
We can just have one `SHRDataTable` component and pass in `tableHeaders` and `data` to be rendered to avoid creating similar tables multiple times

2023-09-21 13:47 UTC, donaldkibet commented on packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
> +                </Tab> */}
I believe this is left out by mistake

2023-09-22 04:28 UTC, PatrickWaweru commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +  data: itemDetails[];
Done

2023-09-22 04:29 UTC, PatrickWaweru commented on packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
> +                </Tab> */}
We don't have medications data yet but it is work in progress by Jacinta

2023-09-22 04:29 UTC, PatrickWaweru commented on packages/esm-shr-app/src/shrpatient-summary/shrpatient-summary.component.tsx
> +import SHRMedicationsDataTable from './shrMedicationsDataTable.component';
Done

2023-09-22 06:54 UTC, PatrickWaweru commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +            </TableBody>
Done

2023-09-22 06:54 UTC, PatrickWaweru commented on packages/esm-shr-app/src/shrpatient-summary/shrAllergiesDataTable.component.tsx
> +  const tableHeaders = ['Allergen', 'Reaction', 'Severity', 'Onset Date', 'Date Recorded'];
Done

2023-09-22 09:22 UTC, CynthiaKamau requested changes
Please fix the linting issues. Otherwise LGTM 🚀

2023-09-22 11:04 UTC, CynthiaKamau approved these changes

2023-09-22 11:06 UTC, merged