Khp3 6538 add peer calendar to 3 x
palladiumkenya/kenyaemr-esm-3.x pull request #375
Opened 2024-10-02 08:28 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

https://github.com/user-attachments/assets/05375771-9b5c-4d87-8e76-b9bc52b9f146

![Screenshot from 2024-10-02 11-16-25](https://github.com/user-attachments/assets/0237aae5-7997-4e2e-a58e-8330168f5dcb)

## Related Issue

https://thepalladiumgroup.atlassian.net/browse/KHP3-6538

## Other

*None.*

2024-10-02 13:15 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +    ...extractAttributeData(relationship[person], config),
I think there is a difference between `contact` and `Peers/Peer educator` hence we should be naming functions and files appropriately

2024-10-02 13:17 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +  includeSelf: boolean,
```suggestion
  includePeerEducator: boolean,
```

2024-10-02 13:18 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +  includeSelf: boolean,
I think self here you mean peer educator right?

2024-10-02 13:19 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +    if (includeSelf && self === null) {
Use of self here will be confusing and in future you might forget what it means. Let's name variable appropriately.

2024-10-02 13:23 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/header/peer-calendar-header.scss
> +  gap: spacing.$spacing-01;
```suggestion
  gap: layout.$spacing-01;
```

2024-10-02 13:23 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/header/peer-calendar-header.scss
> +  padding: spacing.$spacing-03 0 0 0;
```suggestion
  padding: layout.$spacing-03 0 0 0;
```

2024-10-02 13:23 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/header/peer-calendar-metrics.component.tsx
> +          <span>Peer educator:</span>
Make this translatable

2024-10-02 13:24 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/header/peer-calendar-metrics.component.tsx
> +          <strong>Reporting Period</strong>
Same here. Any text should be translatable

2024-10-02 13:26 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-calendar-table-components.component.tsx
> +  contact: Contact;
Should be peer

2024-10-02 13:31 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-calendar-table-components.component.tsx
> +  contact: Contact;
Thanks @Omoshlawi for the good work.  I think we can add filters to the table to be to filter completed, pending etc. Also you might ask Ted to help with UI designs for consistency. Thanks

2024-10-02 13:32 UTC, makombe commented on packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-calendar-table-components.component.tsx
> +  contact: Contact;
UI for managing reporting period to me seems to be off.

2024-10-03 05:02 UTC, Omoshlawi commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +    ...extractAttributeData(relationship[person], config),
@makombe, I was thinking of reusing the hook for contact listing just to avoid code repetation.

2024-10-03 05:06 UTC, Omoshlawi commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +  includeSelf: boolean,
Yes, that the peer educator, just that did not want to name it that way cause reuse of the hook.Let me just introduce a new hook for peers instead then.

2024-10-03 05:09 UTC, Omoshlawi commented on packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-calendar-table-components.component.tsx
> +  contact: Contact;
Ok, I'll reach out to him

2024-10-03 16:13 UTC, ojwanganto commented on packages/esm-patient-clinical-view-app/src/peer-calendar/table/peer-calendar-table-components.component.tsx
> +  contact: Contact;
I actually like the UI but the designers can help further. We can focus on the functionality at this point and have this in.
Thanks

2024-10-04 08:45 UTC, donaldkibet requested changes
Thanks @Omoshlawi

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +  const url = `/ws/rest/v1/relationship?v=${customeRepresentation}&person=${peerEducatorUuid}`;
```suggestion
  const url = `${restBaseUrl}/relationship?v=${customeRepresentation}&person=${peerEducatorUuid}`;
``

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +  const { data, error, isLoading, isValidating } = useSWR<{ data: { results: Relationship[] } }, Error>(
```suggestion
  const { data, error, isLoading, isValidating } = useSWR<{ data: { results: Array<Relationship> } }, Error>(
```
Within OpenMRS 3.x repository the preferred syntax for Array is ``` Array<T> ``` instead of ``` []```

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +          data?.data?.results.filter((rel) => rel.relationshipType.uuid === config.peerEducatorRelationship),
Should we safe guard against undefined at runtime here

```suggestion
          data?.data?.results.filter((rel) => rel?.relationshipType?.uuid === config.peerEducatorRelationship),
```

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +    name: extractName(relationship[person].display),
instead of doing this is it possible to join the person name e.g ``` `${person.firstName} ${person.familyName} ```

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +    startDate: !relationship.startDate ? null : formatDate(parseDate(relationship.startDate)),
If this is to be display on the UI, its better to have the empty placeholder e.g 

```suggestion
    startDate: !relationship.startDate ? '--' : formatDate(parseDate(relationship.startDate)),
```

instead of having it as null

2024-10-04 08:45 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/hooks/useContacts.ts
> +const useContacts = (patientUuid: string) => {
Since we are hitting the relationship endpoint and returning contact. it might be helpful to have some comments to explain what the hook does for easy maintainence or better naming for this hook

2024-10-04 10:03 UTC, Omoshlawi commented on packages/esm-patient-clinical-view-app/src/hooks/usePeers.ts
> +    startDate: !relationship.startDate ? null : formatDate(parseDate(relationship.startDate)),
That is handled at the table level when passing the rows props

2024-10-05 06:56 UTC, Omoshlawi commented
@ojwanganto , @makombe , @donaldkibet , kindly review so that it could be merged and enable me continue with implementing new design for it

2024-10-05 09:43 UTC, ojwanganto commented
> @ojwanganto , @makombe , @donaldkibet , kindly review so that it could be merged and enable me continue with implementing new design for it

This is great work, @Omoshlawi. Thanks so much. I leave it to the other reviewers for syntax reviews

2024-10-07 05:54 UTC, donaldkibet approved these changes

2024-10-07 05:54 UTC, merged