(chore): Removed registration for new body from outside
palladiumkenya/kenyaemr-esm-3.x pull request #394
Opened 2024-10-09 18:55 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
We have agreed on registration for bodies from outside we use the normal patient registration

## Screenshots
![Peek 2024-10-09 21-31](https://github.com/user-attachments/assets/41bbd990-77c1-4d62-9edc-6c91f1f37043)

## Related Issue

*None.*

## Other

*None.*

2024-10-14 06:32 UTC, donaldkibet requested changes

2024-10-14 06:32 UTC, donaldkibet commented on packages/esm-morgue-app/src/index.ts
> +export const addMoreDetailsWorkspace = getAsyncLifecycle(
should we rename this form with a more descriptive name. more details is too generic e.g `patientAdditionalInfoForm`

2024-10-14 06:32 UTC, donaldkibet commented on packages/esm-morgue-app/src/routes.json
> +      "name": "add-more-details-form",
same as here

2024-10-14 06:32 UTC, donaldkibet commented on packages/esm-morgue-app/src/routes.json
> +      "title": "add more details",
we should also try translate the hard coded values here e using `translateFrom` function

2024-10-14 06:32 UTC, donaldkibet commented on packages/esm-morgue-app/src/tables/waiting-queue.component.tsx
> +  const handleMoreDetails = () => {
should this be `admission-workspace` instead of `add-more-details-form`

2024-10-14 10:24 UTC, its-kios09 commented on packages/esm-morgue-app/src/index.ts
> +export const addMoreDetailsWorkspace = getAsyncLifecycle(
sorted

2024-10-14 10:24 UTC, its-kios09 commented
@donaldkibet  Thanks i have sorted it out

2024-10-15 09:58 UTC, donaldkibet approved these changes

2024-10-15 09:58 UTC, merged