(fix): Fixed Pagination Logic in Medical History Panel of Morgue Module
palladiumkenya/kenyaemr-esm-3.x pull request #396
Opened 2024-10-10 18:35 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots
![PaginationMedical](https://github.com/user-attachments/assets/90f39cb6-aaf2-4a48-9247-7f53289efbe3)

## Related Issue

*None.*

## Other

*None.*

2024-10-14 06:05 UTC, donaldkibet requested changes

2024-10-14 06:05 UTC, donaldkibet commented on packages/esm-morgue-app/src/panels/medical-history.component.tsx
> +  const paginatedEncounterItems = useMemo(() => {
would recommend use of server side pagination `useServerPagination` https://github.com/openmrs/openmrs-esm-core/blob/5a6bbe2d83ae675e624a1e9bf332dcda0394cb86/packages/framework/esm-react-utils/src/useOpenmrsPagination.ts#L107

2024-10-14 06:05 UTC, donaldkibet commented on packages/esm-morgue-app/src/panels/medical-history.component.tsx
> +          pageSizes={[5, 10, 20, 50, 100]}
This should not be hard coded

2024-10-14 07:45 UTC, its-kios09 commented
@donaldkibet thanks for suggestions

2024-10-15 10:02 UTC, donaldkibet commented
cc @its-kios09 seems we have some merge conflicts

2024-10-16 01:56 UTC, its-kios09 commented on packages/esm-morgue-app/src/panels/medical-history.component.tsx
> +  const paginatedEncounterItems = useMemo(() => {
Sorted

2024-10-16 02:09 UTC, its-kios09 commented
@donaldkibet i have sorted the pagination let work on the conflicts

2024-10-16 07:28 UTC, donaldkibet commented
Seems we still have conflicts 
![Screenshot 2024-10-16 at 10 27 51](https://github.com/user-attachments/assets/c65176b3-bd84-42ed-ba13-0a839781034d)

2024-10-16 15:09 UTC, its-kios09 commented
@donaldkibet I have sorted the conflicts

2024-10-16 15:09 UTC, its-kios09 commented
@donaldkibet Thanks

2024-10-16 18:27 UTC, donaldkibet requested changes

2024-10-16 18:27 UTC, donaldkibet commented on packages/esm-morgue-app/src/card/compartment.scss
> +// @use '~@openmrs/esm-styleguide/src/vars' as *;
We should remove unused imports

2024-10-16 18:27 UTC, donaldkibet commented on packages/esm-morgue-app/src/details/deceased-details.scss
> +// @import '~@openmrs/esm-styleguide/src/vars';
Same here

2024-10-17 05:47 UTC, donaldkibet approved these changes

2024-10-17 05:47 UTC, merged