Khp3 6721 add ability to search or create a patient from relationship forms
palladiumkenya/kenyaemr-esm-3.x pull request #402
Opened 2024-10-14 05:11 UTC by Omoshlawi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

https://github.com/user-attachments/assets/a52a8ab1-28fa-4650-a0f7-ca6506223443

*None.*

## Related Issue

https://thepalladiumgroup.atlassian.net/browse/KHP3-6721

*None.*

## Other

*None.*

2024-10-14 05:48 UTC, donaldkibet requested changes

2024-10-14 13:19 UTC, Omoshlawi commented
@donaldkibet , What do you think about adding the improved auto suggest component to esm-patient-common-lib for re-usability

[here](https://github.com/palladiumkenya/openmrs-esm-patient-management/blob/main/packages/esm-patient-registration-app/src/patient-registration/input/custom-input/autosuggest/autosuggest.component.tsx) is the initial version but improoved.Used in this PR is its improoved version

2024-10-15 09:59 UTC, donaldkibet commented
> @donaldkibet , What do you think about adding the improved auto suggest component to esm-patient-common-lib for re-usability
> 
> [here](https://github.com/palladiumkenya/openmrs-esm-patient-management/blob/main/packages/esm-patient-registration-app/src/patient-registration/input/custom-input/autosuggest/autosuggest.component.tsx) is the initial version but improoved.Used in this PR is its improoved version

Not sure about it, would using the combo-box component achieve the same thing, we load the items using API. We might want to explore that before lifting the AutoSuggest component to common-lib.

2024-10-15 10:00 UTC, donaldkibet approved these changes

2024-10-15 10:00 UTC, merged