(feat) KHP-6910: Moved deceased details panel into patientChart
palladiumkenya/kenyaemr-esm-3.x pull request #409
Opened 2024-10-17 18:57 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

![updateLinking](https://github.com/user-attachments/assets/ccc4d7f2-ef5f-403d-8a1a-0b24361992aa)

## Related Issue
[[KHP3-6910] Moved deceased details panel into patient Chart - Jira (atlassian.net)](https://thepalladiumgroup.atlassian.net/browse/KHP3-6910)

## Other

*None.*

2024-10-19 12:15 UTC, donaldkibet requested changes
Thanks @its-kios09.

I have observed some extension being exported form `clinic-view-app` that relates to mogue. I would recommend that all features related to mogue module be handled from the app.

I would also recommend only showing the morgue module for patients that are deceased. IMO it doesn't add any value to show that panel for patient still in care. cc @ojwanganto

2024-10-19 12:15 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
> +  slot: 'patient-chart-relationships-slot',
Should rename the slot to a more appropriate name

2024-10-22 07:17 UTC, its-kios09 commented on packages/esm-morgue-app/src/card/avail-compartment.compartment.tsx
> +  const patientChartUrl = '${openmrsSpaBase}/patient/${patientInfo.uuid}/chart/case-management-encounters';
@donaldkibet i suppose to update the PR with new changes lemme look at it then ping you

2024-10-22 07:54 UTC, its-kios09 commented on packages/esm-patient-clinical-view-app/src/dashboard.meta.tsx
> +  slot: 'patient-chart-relationships-slot',
Already done

2024-10-24 20:27 UTC, its-kios09 commented
@donaldkibet I have blocked i have added the condition rendering but the dashboard link disappear but the page appears so, currently I am at WIP

2024-10-28 12:27 UTC, donaldkibet commented
cc @its-kios09 please address the conflicts

2024-10-28 14:35 UTC, its-kios09 commented
> cc @its-kios09 please address the conflicts

sorted

2024-10-28 18:41 UTC, donaldkibet approved these changes

2024-10-28 18:41 UTC, merged