(feat): pre auth form
palladiumkenya/kenyaemr-esm-3.x pull request #421
Opened 2024-10-25 16:02 UTC by amosmachora

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR adds a pre-auth dashboard to view dashboard requests with a `make pre-auth request` form.

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-10-25 16:19 UTC, Omoshlawi requested changes
Thankz @amosmachora , Left some suggestion

2024-10-25 16:19 UTC, Omoshlawi commented on packages/esm-billing-app/src/hooks/use-pre-auth-requests.ts
> +  const url = `https://payers.apeiro-digital.com/api/v1/claim/byFacility?facilityCode=Organization/${mflCodeValue}&type=preauthorization&claimResponseId=`;
Kindly use config `hieBaseUrl`

`const url = `${hieBaseUrl}claim/byFacility?facilityCode=Organization/${mflCodeValue}&type=preauthorization&claimResponseId=``

2024-10-25 16:19 UTC, Omoshlawi commented on packages/esm-billing-app/src/hooks/useInterventions.ts
> +  const url = `https://payers.apeiro-digital.com/api/v1/master/benefit-master/code?searchKey=${code}`;
same here

2024-10-25 16:30 UTC, patryllus approved these changes
Merging for tests. Good work

2024-10-25 16:32 UTC, merged

2024-10-28 05:49 UTC, ojwanganto commented
A screenshot or short video should also be appropriate

2024-10-28 07:12 UTC, amosmachora commented
> A screenshot or short video should also be appropriate

This was done in quite a hurry. Here is a screenshot of the form.
![image](https://github.com/user-attachments/assets/d004abbb-b924-4546-bdc9-a7bc7445e6c4)