(feat) KPH3-7035 : Updating the waiting in line  UI component for deceased persons
palladiumkenya/kenyaemr-esm-3.x pull request #440
Opened 2024-11-05 18:00 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots

![waitinginline](https://github.com/user-attachments/assets/b836f0db-ee4b-4a70-be95-9ac8707ccdac)

## Related Issue
see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-7035

## Other

*None.*

2024-11-05 18:56 UTC, donaldkibet commented
Thanks @its-kios09 we should have the admit and release as an overflow menu items to follow carbon design languge

2024-11-05 19:01 UTC, donaldkibet requested changes
Thanks @its-kios09, left some suggestions.

2024-11-05 19:01 UTC, donaldkibet commented on packages/esm-morgue-app/src/utils/utils.ts
> +  return dayjs(date).format('MMMM DD YYYY, hh:mm A');
Recommend against this, for UI uniformity. We have helper functions from `@openmrs/esm-framework` if we need this we should extend the date formats in `esm-framework`

2024-11-05 21:10 UTC, its-kios09 commented
> Thanks @its-kios09 we should have the admit and release as an overflow menu items to follow carbon design languge

Let me revert to` formatDate() `function

2024-11-05 21:50 UTC, its-kios09 commented on packages/esm-morgue-app/src/tables/generic-table.component.tsx
> +                    {<TableHeader>{''}</TableHeader>}
sorted

2024-11-05 21:51 UTC, its-kios09 commented on packages/esm-morgue-app/src/tables/waiting-queue.component.tsx
> +  const fromHospital = t('waitingInLine', 'Waiting In Line');
sorted

2024-11-05 21:51 UTC, its-kios09 commented on packages/esm-morgue-app/src/tables/waiting-queue.component.tsx
> +    { header: 'Identifier ', key: 'Ids' },
sorted

2024-11-05 21:51 UTC, its-kios09 commented on packages/esm-morgue-app/src/utils/utils.ts
> +  return dayjs(date).format('MMMM DD YYYY, hh:mm A');
reverted

2024-11-06 10:11 UTC, donaldkibet approved these changes

2024-11-06 10:11 UTC, merged