feat KHP3-7051: Implement styling for unsettled bill
palladiumkenya/kenyaemr-esm-3.x pull request #450
Opened 2024-11-07 15:12 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots
![improvements](https://github.com/user-attachments/assets/194f2e94-8edd-4749-8273-ada076118eaf)

## Related Issue
see https://thepalladiumgroup.atlassian.net/browse/KHP3-7051
*None.*

## Other

*None.*

2024-11-08 09:22 UTC, donaldkibet commented
Thanks @its-kios09 how does this look for imaging and procedure orders

2024-11-08 17:43 UTC, its-kios09 commented
@donaldkibet I can updated the UI to attain the uniformity

2024-11-21 20:11 UTC, ojwanganto commented
Do we still need this? @makombe @its-kios09

2024-11-25 09:23 UTC, donaldkibet requested changes

2024-11-25 09:23 UTC, donaldkibet commented on packages/esm-billing-app/src/billable-services/billiable-item/test-order/test-order-action.scss
> +  --cds-layout-size-height: var(--cds-layout-size-height-context);
We should not be directly applying this styles. we should use the type sets [see](https://carbondesignsystem.com/elements/typography/type-sets/)

2024-11-27 05:44 UTC, its-kios09 commented
@donaldkibet I think I will revert the scss styling to maintain the uniformity across the procedure, lab and radiology

2024-11-29 08:49 UTC, its-kios09 commented
Thanks @donaldkibet, I hope the changes haven’t disrupted the layout of the other ESMS. This is what we have collaborated on with the UI/UX design squad from the community.
https://github.com/user-attachments/assets/a43667e7-7c64-487a-9627-d947d8be91cb

2024-12-04 20:40 UTC, ojwanganto commented
@donaldkibet @makombe - please help with reviews. @its-kios09 - fix the conflicts

2024-12-04 21:51 UTC, its-kios09 commented
@ojwanganto sorted

2024-12-05 05:07 UTC, donaldkibet requested changes
@its-kios09 how does the button look like on dispensing app before we merge this in

2024-12-05 08:14 UTC, its-kios09 commented
@donaldkibet It looks the same. The only change I made is aligning the text to the center of the button.

2024-12-09 10:14 UTC, donaldkibet approved these changes

2024-12-09 14:04 UTC, merged