(refactor) follow up changes on the case management: discontinuity of case
palladiumkenya/kenyaemr-esm-3.x pull request #520
Opened 2024-12-17 21:09 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots
![caseUI](https://github.com/user-attachments/assets/73d48ab3-84f2-4470-9157-44318fc14805)

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-12-18 09:02 UTC, ojwanganto commented
Looks OK. Thanks so much.

2024-12-18 09:52 UTC, donaldkibet requested changes

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/modal/end-date.component.tsx
> +import React from 'react';
Why are we adding this abstraction. 

This okay to have in the component that we need the date picker
```tsx
    <Controller
      name={name}
      control={control}
      render={({ field, fieldState }) => (
        <DatePicker datePickerType="single" onChange={(e) => field.onChange(e[0])} className={styles.formDatePicker}>
          <DatePickerInput
            placeholder="mm/dd/yyyy"
            labelText={label || 'End Date'}
            id={`${name}-picker`}
            size="md"
            className={styles.formDatePicker}
            invalid={!!fieldState.error}
            invalidText={fieldState.error?.message}
          />
        </DatePicker>
      )}
    />
```

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/modal/case-management-modal.component.tsx
> +  const [isSubmitting, setIsSubmitting] = useState(false);
No need of handling this state manually. react hook handles this
e.g
```tsx
const {
    handleSubmit, control, formState: { errors, isSubmitting }} = useForm<FormData>({
    resolver: zodResolver(EndRelationshipSchema),
    defaultValues: { endDate: null },
  });
```

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/modal/case-management-modal.component.tsx
> +        title: t('RlshipError', 'Relationship Error'),
```suggestion
        title: t('relationshipError', 'Relationship Error'),
```

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/modal/case-management-modal.component.tsx
> +    required_error: 'End date is required',
should we keep this consistent with standard translations

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/table/case-management-list-active-component.tsx
> +  const { data: activeCasesData, error: activeCasesError, mutate: fetchCases } = useActivecases(caseManagerPersonUuid);
Are we using mutate anywhere in this component

2024-12-18 09:52 UTC, donaldkibet commented on packages/esm-patient-clinical-view-app/src/case-management/table/case-management-list-inactive-component.tsx
> +      <Tag type="red" size="lg">
should we have the size be responsive for both large desktop and tablet e.g
```tsx
const responsiveSize = useLayoutType() === 'tablet' ? 'md' : 'lg';
```

2024-12-19 09:27 UTC, its-kios09 commented on packages/esm-patient-clinical-view-app/src/case-management/modal/end-date.component.tsx
> +import React from 'react';
sorted

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: '5b9e6cd1-f836-4144-91e4-401c58dd62af',
These are related to morgue functions

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: '163084AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
and this

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: 'd889f05b-0d9b-462f-ae8e-2e9be79fd954',
and this

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: 'f2b35679-7ba9-4619-92cb-6872b0c6bf57',
and this

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: 'da524812-5600-4677-ba26-eb61eb925eef',
and this

2025-01-10 04:46 UTC, ojwanganto commented on packages/esm-morgue-app/src/config-schema.ts
> +    _default: '0dffecb3-2dc4-4d56-8cd4-56ba38579c69',
and this

2025-01-10 12:51 UTC, its-kios09 commented
@ojwanganto I tried to remove the files seems it is breaking most of the case management functionality I have created a reference PR for this, so, that I can close this

2025-01-10 12:51 UTC, closed without merging